// ── Custom Cursor ──────────────────────────────────────────────
const cur = document.getElementById('cur');
const ring = document.getElementById('cring');
let mx = 0, my = 0, rx = 0, ry = 0;
document.addEventListener('mousemove', e => { mx = e.clientX; my = e.clientY; cur.style.left = mx+'px'; cur.style.top = my+'px'; });
(function animRing() {
  rx += (mx - rx) * 0.12; ry += (my - ry) * 0.12;
  ring.style.left = rx+'px'; ring.style.top = ry+'px';
  requestAnimationFrame(animRing);
})();
document.querySelectorAll('a,button,.faq-q,.lang-option').forEach(el => {
  el.addEventListener('mouseenter', () => ring.classList.add('hover'));
  el.addEventListener('mouseleave', () => ring.classList.remove('hover'));
});

// ── (Mascots replace Three.js gems — no JS needed) ──────────

// ── Scroll Reveal ──────────────────────────────────────────────
const revealObs = new IntersectionObserver(entries => {
  entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('vis'); revealObs.unobserve(e.target); } });
}, { threshold: 0.1 });
document.querySelectorAll('.reveal').forEach(el => revealObs.observe(el));

// ── FAQ Toggle ─────────────────────────────────────────────────
function toggle(el) {
  const item = el.parentElement;
  const isOpen = item.classList.contains('open');
  document.querySelectorAll('.faq-item.open').forEach(i => i.classList.remove('open'));
  if (!isOpen) item.classList.add('open');
}

// ── Language Switcher ──────────────────────────────────────────
const langBtn = document.getElementById('langBtn');
const langDropdown = document.getElementById('langDropdown');
const langLabel = document.getElementById('langLabel');

langBtn.addEventListener('click', e => {
  e.stopPropagation();
  langDropdown.classList.toggle('open');
});
document.addEventListener('click', () => langDropdown.classList.remove('open'));

document.querySelectorAll('.lang-option').forEach(opt => {
  opt.addEventListener('click', () => {
    const lang = opt.dataset.lang;
    document.querySelectorAll('.lang-option').forEach(o => o.classList.remove('active'));
    opt.classList.add('active');
    langLabel.textContent = lang.toUpperCase();
    langDropdown.classList.remove('open');
    applyLang(lang);
  });
});

// ── Translations ───────────────────────────────────────────────
const T = {
  en: {
    nav_sub: 'Community Hub',
    nav_about: 'About',
    nav_hunt: 'Hunt',
    nav_roles: 'Roles',
    nav_token: 'Token',
    nav_team: 'Team',
    nav_news: 'News',
    nav_discord: '↗ Discord',
    hero_tag: '🌍 Global Community',
    hero_sub: 'Everything about <strong>Dlicom</strong> — a decentralized platform with DeFi, crypto wallet and social network. Guides, FAQ and news for the global community.',
    hero_btn1: '↗ Join Discord',
    hero_btn2: 'Project Website',
    scroll: 'scroll',
    stat_token: 'Token',
    stat_platform: 'Platform',
    stat_supply: 'Total Supply',
    stat_standard: 'Standard',
    mascot_title: 'Meet Dili',
    mascot_desc: 'The official Dlicom mascot — the face of SocialFi. Create a story, lore or concept about him and earn the <strong>Dliever</strong> role. Any format: text, video, art.',
    mascot_btn: 'Branding →',
    sec_what: 'What is <span class="acc">Dlicom</span>',
    feat1_title: 'Social Network',
    feat1_desc: 'Publish posts, chat in encrypted messages, earn tips in DLI tokens. A censorship-resistant alternative to traditional social networks.',
    feat2_title: 'Crypto Wallet',
    feat2_desc: 'Self-custody wallet with crypto and NFT support. Best-rate swaps, pay gas fees with DLI tokens, send directly in chat.',
    feat3_title: 'DeFi & Staking',
    feat3_desc: 'Stake DLI tokens for USDT rewards. Multiple periods available. Access dApps via built-in Web3 browser.',
    sec_start: 'How to <span class="acc">Start</span>',
    step1_title: 'Download the App',
    step1_desc: 'Available on <a href="https://apps.apple.com/us/app/dlicom/id6502626332" target="_blank">App Store</a> and <a href="https://play.google.com/store/search?q=dlicom&c=apps" target="_blank">Google Play</a>. Developer: Shlenpower Pte. Ltd.',
    step2_title: 'Create a Wallet',
    step2_desc: 'During registration, create a new wallet or import an existing one. Save your seed phrase in a safe place — recovery without it is impossible.',
    step3_title: 'Join Discord',
    step3_desc: 'Join the <a href="https://discord.gg/BmYmRXc8" target="_blank">official server</a>. Choose your region to unlock the right channels.',
    step4_title: 'Become an Active Member',
    step4_desc: 'Participate in activities, help newcomers, join the Regional Hunt — earn Dliever, Dcoded and DCO roles.',
    sec_hunt: 'Regional Lead <span class="acc">Hunt</span>',
    hunt_title: 'Become Regional Lead or Mod',
    hunt_desc: 'The moment anyone can become a leader of their region. Work with the team, earn roles and shape the community. Right now — no moderators, no leads. The spot is open.',
    hunt_apply: 'Apply Now',
    hunt_discord: 'Go to Discord',
    hrole1_desc: 'Community manager of your region. Responsible for growth, retention, positioning, managing regional campaigns and analytics.',
    hrole2_desc: "Leader's assistant. Answers questions, guides members, runs events and keeps the chat active.",
    hrole3_desc: 'Active content creators and contributors. Building games, websites, helping the team. Mostly active in <strong>#creators</strong> and <strong>#dlicom-creators</strong>.',
    hrole4_tag: '🔹 Junior Hunter',
    hrole4_desc: 'Fill the form and get this special role — grants access to <strong>#nominations</strong> and other private channels.',
    hrole4_link: 'Fill the form →',
    sec_phases: 'Hunt <span class="acc">Phases</span>',
    phase1_label: 'Phase 1',
    phase1_title: 'Make Your Mark',
    phase1_dates: '27 FEB — 11 MAR',
    phase1_desc: 'Initial selection. Nominations channel opens. The team observes, helps and guides everyone in the right direction.',
    phase1_li1: '10 Dliever roles per region',
    phase1_li2: 'Nominations open for form fillers',
    phase1_li3: 'Junior Hunter role available',
    phase2_label: 'Phase 2',
    phase2_title: 'Trial Period',
    phase2_dates: '12 MAR — 19 MAR',
    phase2_desc: 'Top 5 candidates per region start working with the community team. Selected candidates can nominate people for Dliever and Dcoded.',
    phase2_li1: '5 Dcoded roles per region',
    phase2_li2: 'Only a Dliever can receive Dcoded',
    phase2_li3: 'Direct team collaboration',
    phase3_label: 'Phase 3',
    phase3_title: 'Final',
    phase3_dates: '20 MAR — 27 MAR',
    phase3_desc: 'Leads and mods in place, roles and permissions assigned. The hardest role — Dlicom Contribution Officer — becomes available.',
    phase3_li1: '1 DCO role per region',
    phase3_li2: 'Must have Dcoded + Dlicom server tag',
    phase3_li3: 'Regional Lead & Helper assigned',
    results_title: 'Per region results',
    res_p1: '(Phase 1)',
    res_p2: '(Phase 2)',
    res_p3: '(Phase 3)',
    sec_roles: 'Community <span class="acc">Roles</span>',
    role1_desc: 'Pioneers who proved their reliability and knowledge of Dlicom. The most sought-after base role — the start of everything.',
    role2_desc: 'Active and dedicated members — an example for newcomers. Requires Dliever role.',
    role3_desc: 'Dlicom Contribution Officer. The rarest role. Requires Dcoded + server tag.',
    role4_desc: 'Legendary first 1000 users. Airdrop boost, bonus XP. No longer awarded.',
    sec_rules: 'Community <span class="acc">Rules</span>',
    rule1_title: 'Prohibited',
    rule1_desc: 'Politics, racism, discrimination. NSFW content. Spam and self-promotion. Off-topic in themed channels.',
    rule2_title: 'Welcome',
    rule2_desc: 'Help newcomers, grow yourself, build connections. Turn ideas into action. Be yourself.',
    rule3_title: 'Beware of Scams',
    rule3_desc: 'The Dlicom team will <strong>never message you first in DMs</strong>. Always verify.',
    rule4_title: 'Community Principle',
    rule4_desc: 'Value is everything. The <strong>#creators</strong> channel is the most reliable way to earn a role.',
    sec_token: 'Tokeno<span class="acc">mics</span>',
    leg1: 'Network Sale',
    leg2: 'Public Pre Sale',
    leg3: 'Liquidity',
    leg4: 'Public Sale',
    leg5: 'Treasury & Reserve',
    leg6: 'Ecosystem / Expenses',
    leg7: 'Founders and Team',
    leg8: 'Community / Users Incentives',
    leg9: 'Advisory',
    sec_tokdet: 'Token Details <span class="acc">$DLI</span>',
    tok_standard: 'Standard',
    tok_supply: 'Total Supply',
    tok_price: 'Initial Price',
    tok_circ: 'Initial Circulation',
    tok_cap: 'Initial Market Cap',
    tok_lp: 'Liquidity Pool',
    tok_vest: 'Vesting',
    tok_vest_val: '0–60 months',
    tok_dec: 'Decimals',
    sec_team: 'Dlicom <span class="acc">Team</span>',
    team1_role: 'Chairman & Co-Founder',
    team2_role: 'Head of Tokenomics',
    team3_role: 'Community Manager',
    team4_role: 'Product Manager',
    sec_faq: 'Frequently Asked <span class="acc">Questions</span>',
    faq0_q: 'What is the Junior Hunter role?',
    faq0_a: 'Fill out the <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">application form</a> and get the Junior Hunter role — it grants access to <strong>#nominations</strong> and other private channels during the Hunt.',
    faqA_q: 'What is the difference between Regional Lead and Regional Helper?',
    faqA_a: '<strong>Regional Lead</strong> is the community manager of their region: growth, retention, campaigns, analytics. <strong>Regional Helper</strong> is the leader\'s assistant: answers questions, guides members, runs events, keeps the chat active.',
    faq1_q: 'How to become Regional Lead?',
    faq1_a: '1. Fill out the <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">application form</a>. 2. In Discord, choose your region. 3. Actively participate in all three phases (27 Feb — 27 Mar).',
    faq2_q: 'Is Dliever required to join the Regional Hunt?',
    faq2_a: 'No. Dliever is not required to apply. But active participants earn it automatically and have priority in selection.',
    faq3_q: 'What is the DLI token?',
    faq3_a: 'DLI is Dlicom\'s native token on Ethereum. Used for: sending crypto in chat, tips, gas payments, staking with USDT rewards, and voting.',
    faq4_q: 'Is KYC required?',
    faq4_a: 'No. Dlicom is a fully decentralized project operating as a DEX. No KYC required. Profiles are based on Ethereum addresses.',
    faq5_q: 'What is the Dili mascot contest?',
    faq5_a: 'Create a story, lore or concept about Dili (text, video, art). The best 10 ideas earn the Dliever role. Publish in <code>#creators</code>, quoting the <a href="https://x.com/DlicomApp/status/2023744462434783676" target="_blank">X post</a>.',
    faq6_q: 'How to earn on the platform?',
    faq6_a: '<code>Staking</code> — DLI for USDT rewards. <code>Content</code> — tips from followers. <code>Referrals</code> — invite via your code.',
    faq7_q: 'Can I apply for Regional Lead directly, skipping Helper?',
    faq7_a: 'Yes. By applying for Regional Lead, you automatically become a candidate for Regional Helper as well.',
    faq8_q: 'Why is now the best time to join?',
    faq8_a: "It's the earliest stage — no moderators, no leads in regions yet. Starting from zero right now is the best window to become a Regional Lead or Helper.",
    sec_links: 'Official <span class="acc">Links</span>',
    link_wp: 'Whitepaper',
    link_tgoff: 'Telegram Official',
    link_tgcis: 'Telegram CIS',
    link_yt: 'YouTube',
    link_med: 'Medium Blog',
    sec_news: 'Discord <span class="acc">Updates</span>',
    news1_date: '2 MAR 2025',
    news_badge_new: 'NEW',
    news1_title: '📌 #content-spotlight — raid selection',
    news1_body: 'A new channel <strong>#content-spotlight</strong> has appeared in Discord — a dedicated showcase for the best community content. Moderators will hand-pick creators\' posts and feature them there, then organize a full raid on the top works. If your post makes it into <strong>#content-spotlight</strong>, the team considers it worthy of maximum reach. This is your chance to stand out among hundreds of Hunt participants and get on the team\'s radar. Post, put in the effort — and the next raid might just be on you.',
    news_tag_announce: '📣 Announcement',
    news2_date: '27 FEB 2025',
    news_badge_phase1: 'PHASE 1',
    news2_title: '🚀 Regional Hunt launched',
    news2_body: 'Applications for Regional Lead and Regional Helper are now officially open. The <strong>#nominations</strong> channel is unlocked for Junior Hunter role holders. Apply now and be among the first.',
    news_tag_hunt: '🏹 Hunt',
    news3_date: 'FEB 2025',
    news_badge_info: 'INFO',
    news3_title: '🎭 Dili lore contest',
    news3_body: 'Create a story, art or concept about the Dili mascot. The best 10 entries automatically earn the <strong>Dliever</strong> role. Post in <code>#creators</code> quoting the official X post.',
    news_tag_creators: '🎨 Creators',
    news4_date: '5 MAR 2025',
    news4_title: '🛡️ Test Moderators Appointed',
    news4_body: '6 test moderators have been appointed in the Discord server. After a 2-week trial period, 2 of them will remain as permanent moderators. The selection process is underway — the best will stay.',
    news_tag_mod: '🛡️ Moderation',
    cta_title: 'Ready to join the Community Hub?',
    cta_desc: 'Join Discord, choose your region and participate in the Regional Hunt',
    cta_btn1: '↗ Open Discord',
    cta_btn2: 'Apply Now',
    footer_brand: 'Community Hub · Unofficial Resource',
    footer_apply: 'Application Form',
    footer_discord: '',
    footer_discord_txt: 'Join the Server',
    nav_tg_news: 'TG NEWS',
    tg_post_title: '<strong>Regional Hunt: the next stage will be 11 March! 🗺️</strong>',
    tg_post_body: 'Season 1 ends today at 00:00 UTC across Russia, Ukraine, Nigeria, Vietnam, Arabic, and India. If you\'re a creator, contributor, regional grinder, or community builder, now\'s time!',
    tg_news_open: 'Open Discord',
    tg_post_form: '👉 Dlicom Discord',
    news10_date: '10 MAR 2025',
    news10_title: '🗺️ Regional Hunt: the next stage will be 11 March!',
    news10_body: 'Season 1 ends today at 00:00 UTC across Russia, Ukraine, Nigeria, Vietnam, Arabic, and India. If you\'re a creator, contributor, regional grinder, or community builder, now\'s time!',
    news10_btn: 'Dlicom Discord →',
    news7_date: '8 MAR 2025',
    news7_title: '🎯 Phase 1 Wrapping Up — Here\'s How Roles Work',
    news7_body: 'On March 11, Phase 1 ends. ~60 <strong>Dliever</strong> and ~30 trial spots will be selected. <strong>Regional Lead</strong> — face of your region, growth & community management. <strong>Regional Helper (Mod)</strong> — translations, events, moderation. <strong>Dliever & other roles</strong> — content creation in <code>#creators</code>. Quality work gets featured in <code>#content-spotlight</code>.',
    news7_btn: 'Fill the Form →',
    news8_date: '8 MAR 2025',
    news8_title: '📺 Weekly Community Spotlight — Live Review',
    news8_body: 'March 8 at 19:00 — the team goes live to review the best community work and give real feedback on content quality and Discord activity. <a href="https://docs.google.com/forms/d/e/1FAlpQLSc1cJCwTX-bJc1R41CMucUuTGMrYdlqjQXq03aoArXEz3cyyg/viewform" target="_blank">Submit your work</a> to get featured.',
    news9_date: '7 MAR 2025',
    news9_title: '💼 Hiring: Part-time SMM Teammate',
    news9_body: 'Dlicom is looking for a part-time SMM team member. Must be comfortable in Web3, follow trends, and create native content for X and Telegram. Deadline: March 20. <a href="https://forms.gle/qvBF4vKm8ynGPD618" target="_blank">Apply here</a>.',
    news_tag_team: '💼 Team',
  },

  ru: {
    nav_sub: 'Хаб Сообщества',
    nav_about: 'О нас',
    nav_hunt: 'Хант',
    nav_roles: 'Роли',
    nav_token: 'Токен',
    nav_team: 'Команда',
    nav_news: 'Новости',
    nav_discord: '↗ Discord',
    hero_tag: '🌍 Глобальное сообщество',
    hero_sub: 'Всё о <strong>Dlicom</strong> — децентрализованной платформе с DeFi, криптокошельком и соцсетью. Гайды, FAQ и новости для глобального сообщества.',
    hero_btn1: '↗ Войти в Discord',
    hero_btn2: 'Сайт проекта',
    scroll: 'скролл',
    stat_token: 'Токен',
    stat_platform: 'Платформа',
    stat_supply: 'Общий запас',
    stat_standard: 'Стандарт',
    mascot_title: 'Знакомьтесь — Дили',
    mascot_desc: 'Официальный маскот Dlicom — лицо SocialFi. Создай историю, лор или концепт о нём и получи роль <strong>Dliever</strong>. Любой формат: текст, видео, арт.',
    mascot_btn: 'Брендинг →',
    sec_what: 'Что такое <span class="acc">Dlicom</span>',
    feat1_title: 'Социальная сеть',
    feat1_desc: 'Публикуй посты, общайся в зашифрованных сообщениях, получай чаевые в токенах DLI. Альтернатива традиционным соцсетям без цензуры.',
    feat2_title: 'Криптокошелёк',
    feat2_desc: 'Self-custody кошелёк с поддержкой крипты и NFT. Свапы по лучшему курсу, оплата газа токенами DLI, отправка прямо в чате.',
    feat3_title: 'DeFi и Стейкинг',
    feat3_desc: 'Стейкинг DLI токенов за вознаграждения в USDT. Несколько периодов. Доступ к dApps через встроенный Web3 браузер.',
    sec_start: 'Как <span class="acc">начать</span>',
    step1_title: 'Скачай приложение',
    step1_desc: 'Доступно в <a href="https://apps.apple.com/us/app/dlicom/id6502626332" target="_blank">App Store</a> и <a href="https://play.google.com/store/search?q=dlicom&c=apps" target="_blank">Google Play</a>. Разработчик: Shlenpower Pte. Ltd.',
    step2_title: 'Создай кошелёк',
    step2_desc: 'При регистрации создай новый кошелёк или импортируй существующий. Сохрани сид-фразу в надёжном месте — без неё восстановление невозможно.',
    step3_title: 'Войди в Discord',
    step3_desc: 'Вступи в <a href="https://discord.gg/BmYmRXc8" target="_blank">официальный сервер</a>. Выбери свой регион для доступа к нужным каналам.',
    step4_title: 'Стань активным участником',
    step4_desc: 'Участвуй в активностях, помогай новичкам, присоединись к Regional Hunt — получай роли Dliever, Dcoded и DCO.',
    sec_hunt: 'Regional Lead <span class="acc">Хант</span>',
    hunt_title: 'Стань Regional Lead или Модератором',
    hunt_desc: 'Момент, когда каждый может стать лидером своего региона. Работай с командой, получай роли и формируй сообщество. Прямо сейчас — нет модераторов, нет лидов. Место свободно.',
    hunt_apply: 'Подать заявку',
    hunt_discord: 'Перейти в Discord',
    hrole1_desc: 'Менеджер сообщества своего региона. Отвечает за рост, удержание, позиционирование, управление региональными кампаниями и аналитику.',
    hrole2_desc: 'Помощник лидера. Отвечает на вопросы, помогает участникам, проводит ивенты и поддерживает активность в чате.',
    hrole3_desc: 'Активные создатели контента и контрибьюторы. Делают игры, сайты, помогают команде. Преимущественно активны в <strong>#creators</strong> и <strong>#dlicom-creators</strong>.',
    hrole4_tag: '🔹 Начинающий охотник',
    hrole4_desc: 'Заполни форму и получи эту особую роль — она даёт доступ к <strong>#nominations</strong> и другим приватным каналам.',
    hrole4_link: 'Заполнить форму →',
    sec_phases: '<span class="acc">Фазы</span> ханта',
    phase1_label: 'Фаза 1',
    phase1_title: 'Заяви о себе',
    phase1_dates: '27 ФЕВ — 11 МАР',
    phase1_desc: 'Начальный отбор. Открывается канал номинаций. Команда наблюдает, помогает и направляет всех в нужную сторону.',
    phase1_li1: '10 ролей Dliever на регион',
    phase1_li2: 'Номинации открыты для заполнивших форму',
    phase1_li3: 'Роль Начинающего охотника доступна',
    phase2_label: 'Фаза 2',
    phase2_title: 'Испытательный период',
    phase2_dates: '12 МАР — 19 МАР',
    phase2_desc: 'Топ-5 кандидатов по регионам начинают работать с командой сообщества. Выбранные кандидаты могут номинировать людей на Dliever и Dcoded.',
    phase2_li1: '5 ролей Dcoded на регион',
    phase2_li2: 'Только Dliever может получить Dcoded',
    phase2_li3: 'Прямое взаимодействие с командой',
    phase3_label: 'Фаза 3',
    phase3_title: 'Финал',
    phase3_dates: '20 МАР — 27 МАР',
    phase3_desc: 'Лиды и модераторы назначены, роли и права выданы. Становится доступна самая сложная роль — Dlicom Contribution Officer.',
    phase3_li1: '1 роль DCO на регион',
    phase3_li2: 'Необходим Dcoded + тег сервера Dlicom',
    phase3_li3: 'Назначены Regional Lead и Helper',
    results_title: 'Результаты на регион',
    res_p1: '(Фаза 1)',
    res_p2: '(Фаза 2)',
    res_p3: '(Фаза 3)',
    sec_roles: 'Роли <span class="acc">сообщества</span>',
    role1_desc: 'Первопроходцы, доказавшие надёжность и знание Dlicom. Самая желанная базовая роль — начало всего.',
    role2_desc: 'Активные и преданные участники — пример для новичков. Требует роль Dliever.',
    role3_desc: 'Dlicom Contribution Officer. Самая редкая роль. Требует Dcoded + тег сервера.',
    role4_desc: 'Легендарные первые 1000 пользователей. Буст аирдропа, бонусный XP. Больше не выдаётся.',
    sec_rules: 'Правила <span class="acc">сообщества</span>',
    rule1_title: 'Запрещено',
    rule1_desc: 'Политика, расизм, дискриминация. NSFW контент. Спам и самореклама. Оффтоп в тематических каналах.',
    rule2_title: 'Приветствуется',
    rule2_desc: 'Помогай новичкам, развивайся сам, выстраивай связи. Превращай идеи в действия. Будь собой.',
    rule3_title: 'Осторожно: скамеры',
    rule3_desc: 'Команда Dlicom <strong>никогда не напишет тебе первой в личку</strong>. Всегда проверяй.',
    rule4_title: 'Принцип сообщества',
    rule4_desc: 'Ценность — это всё. Канал <strong>#creators</strong> — самый надёжный способ получить роль.',
    sec_token: 'Токено<span class="acc">мика</span>',
    leg1: 'Сетевая продажа',
    leg2: 'Публичная пресейл',
    leg3: 'Ликвидность',
    leg4: 'Публичная продажа',
    leg5: 'Казначейство и резерв',
    leg6: 'Экосистема / Расходы',
    leg7: 'Основатели и команда',
    leg8: 'Сообщество / Стимулы пользователей',
    leg9: 'Консультанты',
    sec_tokdet: 'Детали токена <span class="acc">$DLI</span>',
    tok_standard: 'Стандарт',
    tok_supply: 'Общий запас',
    tok_price: 'Начальная цена',
    tok_circ: 'Начальное обращение',
    tok_cap: 'Начальная рыночная кап.',
    tok_lp: 'Пул ликвидности',
    tok_vest: 'Вестинг',
    tok_vest_val: '0–60 месяцев',
    tok_dec: 'Десятичные знаки',
    sec_team: 'Команда <span class="acc">Dlicom</span>',
    team1_role: 'Председатель и сооснователь',
    team2_role: 'Руководитель по токеномике',
    team3_role: 'Менеджер сообщества',
    team4_role: 'Менеджер продукта',
    sec_faq: 'Часто задаваемые <span class="acc">вопросы</span>',
    faq0_q: 'Что такое роль «Начинающий охотник»?',
    faq0_a: 'Заполни <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">форму заявки</a> и получи роль Начинающего охотника — она даёт доступ к <strong>#nominations</strong> и другим приватным каналам во время Ханта.',
    faqA_q: 'В чём разница между Regional Lead и Regional Helper?',
    faqA_a: '<strong>Regional Lead</strong> — менеджер сообщества своего региона: рост, удержание, кампании, аналитика. <strong>Regional Helper</strong> — помощник лидера: отвечает на вопросы, помогает участникам, проводит ивенты, поддерживает активность в чате.',
    faq1_q: 'Как стать Regional Lead?',
    faq1_a: '1. Заполни <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">форму заявки</a>. 2. В Discord выбери свой регион. 3. Активно участвуй во всех трёх фазах (27 фев — 27 мар).',
    faq2_q: 'Нужна ли роль Dliever для участия в Regional Hunt?',
    faq2_a: 'Нет. Dliever не обязателен для подачи заявки. Но активные участники получают её автоматически и имеют приоритет при отборе.',
    faq3_q: 'Что такое токен DLI?',
    faq3_a: 'DLI — нативный токен Dlicom на Ethereum. Используется для: отправки крипты в чате, чаевых, оплаты газа, стейкинга с USDT-наградами и голосования.',
    faq4_q: 'Нужно ли KYC?',
    faq4_a: 'Нет. Dlicom — полностью децентрализованный проект, работающий как DEX. KYC не требуется. Профили основаны на адресах Ethereum.',
    faq5_q: 'Что такое конкурс маскота Дили?',
    faq5_a: 'Создай историю, лор или концепт о Дили (текст, видео, арт). Лучшие 10 идей получают роль Dliever. Публикуй в <code>#creators</code>, цитируя <a href="https://x.com/DlicomApp/status/2023744462434783676" target="_blank">X пост</a>.',
    faq6_q: 'Как зарабатывать на платформе?',
    faq6_a: '<code>Стейкинг</code> — DLI за USDT-награды. <code>Контент</code> — чаевые от подписчиков. <code>Рефералы</code> — приглашай по своему коду.',
    faq7_q: 'Можно ли подать заявку сразу на Regional Lead, минуя Helper?',
    faq7_a: 'Да. Подавая заявку на Regional Lead, ты автоматически становишься кандидатом и на Regional Helper.',
    faq8_q: 'Почему сейчас лучшее время для вступления?',
    faq8_a: 'Это самый ранний этап — в регионах пока нет модераторов и лидов. Начать с нуля прямо сейчас — лучшее окно, чтобы стать Regional Lead или Helper.',
    sec_links: 'Официальные <span class="acc">ссылки</span>',
    link_wp: 'Вайтпейпер',
    link_tgoff: 'Telegram Официальный',
    link_tgcis: 'Telegram СНГ',
    link_yt: 'YouTube',
    link_med: 'Блог на Medium',
    sec_news: 'Обновления <span class="acc">Discord</span>',
    news1_date: '2 МАР 2025',
    news_badge_new: 'НОВОЕ',
    news1_title: '📌 #content-spotlight — рейд-выборка',
    news1_body: 'В Discord появился новый канал <strong>#content-spotlight</strong> — витрина лучшего контента сообщества. Модераторы будут отбирать посты создателей и публиковать их там, а затем организовывать полноценный рейд на топовые работы. Если твой пост попадёт в <strong>#content-spotlight</strong>, команда считает его достойным максимального охвата. Это твой шанс выделиться среди сотен участников Ханта и попасть в поле зрения команды. Публикуй, старайся — и следующий рейд может быть на тебя.',
    news_tag_announce: '📣 Объявление',
    news2_date: '27 ФЕВ 2025',
    news_badge_phase1: 'ФАЗА 1',
    news2_title: '🚀 Regional Hunt запущен',
    news2_body: 'Заявки на Regional Lead и Regional Helper официально открыты. Канал <strong>#nominations</strong> разблокирован для обладателей роли Начинающего охотника. Подавай заявку сейчас и будь в числе первых.',
    news_tag_hunt: '🏹 Хант',
    news3_date: 'ФЕВ 2025',
    news_badge_info: 'ИНФО',
    news3_title: '🎭 Конкурс лора Дили',
    news3_body: 'Создай историю, арт или концепт о маскоте Дили. Лучшие 10 работ автоматически получают роль <strong>Dliever</strong>. Публикуй в <code>#creators</code>, цитируя официальный X пост.',
    news_tag_creators: '🎨 Создатели',
    news4_date: '5 МАР 2025',
    news4_title: '🛡️ Назначены тестовые модераторы',
    news4_body: 'На сервере Discord назначены 6 тестовых модераторов. После двухнедельного испытательного периода из них останутся 2 постоянных модератора. Отбор идёт — лучшие останутся.',
    news_tag_mod: '🛡️ Модерация',
    news5_date: '5 МАР 2025',
    news5_title: '🏆 Турнир по CS2 — СНГ регион',
    news5_body: '5 марта в 19:00 по МСК пройдёт турнир по CS2 в регионе СНГ. Подать заявку на участие можно по ссылке ниже.',
    news5_btn: '📋 Подать заявку',
    news_tag_tournament: '🏆 Турнир',
    cta_title: 'Готов присоединиться к Community Hub?',
    cta_desc: 'Войди в Discord, выбери регион и участвуй в Regional Hunt',
    cta_btn1: '↗ Открыть Discord',
    cta_btn2: 'Подать заявку',
    footer_brand: 'Community Hub · Неофициальный ресурс',
    footer_apply: 'Форма заявки',
    footer_discord: '',
    footer_discord_txt: 'Войти на сервер',
    nav_tg_news: 'TG НОВОСТИ',
    tg_post_title: '<strong>Regional Hunt: следующий этап — 11 марта! 🗺️</strong>',
    tg_post_body: 'Сезон 1 заканчивается сегодня в 00:00 UTC для России, Украины, Нигерии, Вьетнама, арабского региона и Индии. Если ты создатель, контрибьютор или строитель сообщества — сейчас твоё время!',
    tg_news_open: 'Открыть Discord',
    tg_post_form: '👉 Discord Dlicom',
    news10_date: '10 МАР 2025',
    news10_title: '🗺️ Regional Hunt: следующий этап — 11 марта!',
    news10_body: 'Сезон 1 заканчивается сегодня в 00:00 UTC для России, Украины, Нигерии, Вьетнама, арабского региона и Индии. Если ты создатель, контрибьютор или строитель сообщества — сейчас твоё время!',
    news10_btn: 'Discord Dlicom →',
    news7_date: '8 МАР 2025',
    news7_title: '🎯 Фаза 1 завершается — как работают роли',
    news7_body: '11 марта завершается Фаза 1. Будут отобраны ~60 <strong>Dliever</strong> и ~30 мест на испытательный срок. <strong>Regional Lead</strong> — лицо региона, рост и управление сообществом. <strong>Regional Helper (Mod)</strong> — переводы, ивенты, модерация. <strong>Dliever и другие роли</strong> — создание контента в <code>#creators</code>. Лучшие работы попадают в <code>#content-spotlight</code>.',
    news7_btn: 'Заполнить форму →',
    news8_date: '8 МАР 2025',
    news8_title: '📺 Еженедельный Community Spotlight — прямой эфир',
    news8_body: '8 марта в 19:00 — команда выходит в прямой эфир для обзора лучших работ сообщества и обратной связи по качеству контента и активности в Discord. <a href="https://docs.google.com/forms/d/e/1FAlpQLSc1cJCwTX-bJc1R41CMucUuTGMrYdlqjQXq03aoArXEz3cyyg/viewform" target="_blank">Отправить работу</a>.',
    news9_date: '7 МАР 2025',
    news9_title: '💼 Вакансия: SMM-специалист (part-time)',
    news9_body: 'Dlicom ищет SMM-специалиста на part-time. Нужно разбираться в Web3, следить за трендами и создавать нативный контент для X и Telegram. Дедлайн: 20 марта. <a href="https://forms.gle/qvBF4vKm8ynGPD618" target="_blank">Подать заявку</a>.',
    news_tag_team: '💼 Команда',
  },

  ar: {
    nav_sub: 'مركز المجتمع',
    nav_about: 'حول',
    nav_hunt: 'الصيد',
    nav_roles: 'الأدوار',
    nav_token: 'التوكن',
    nav_team: 'الفريق',
    nav_news: 'الأخبار',
    nav_discord: '↗ ديسكورد',
    hero_tag: '🌍 مجتمع عالمي',
    hero_sub: 'كل شيء عن <strong>Dlicom</strong> — منصة لامركزية تجمع بين التمويل اللامركزي، محفظة العملات المشفرة، والشبكة الاجتماعية. أدلة ومحتوى تعليمي وأخبار للمجتمع العالمي.',
    hero_btn1: '↗ انضم إلى ديسكورد',
    hero_btn2: 'الموقع الرسمي',
    scroll: 'تمرير',
    stat_token: 'توكن',
    stat_platform: 'منصة',
    stat_supply: 'إجمالي المعروض',
    stat_standard: 'المعيار',
    mascot_title: 'تعرف على Dili',
    mascot_desc: 'الشخصية الرسمية لـ Dlicom — رمز الشبكة الاجتماعية المالية. أنشئ قصة أو عالمًا خياليًا أو مفهومًا عنه واحصل على دور <strong>Dliever</strong>. أي صيغة: نص، فيديو، فن.',
    mascot_btn: 'الهوية البصرية ←',
    sec_what: 'ما هو <span class="acc">Dlicom</span>',
    feat1_title: 'شبكة اجتماعية',
    feat1_desc: 'انشر المنشورات، تواصل عبر رسائل مشفرة، واكسب إكراميات بتوكنات DLI. بديل مقاوم للرقابة عن الشبكات الاجتماعية التقليدية.',
    feat2_title: 'محفظة عملات مشفرة',
    feat2_desc: 'محفظة ذاتية الحراسة تدعم العملات المشفرة و NFT. أفضل أسعار التحويل، دفع رسوم الغاز بتوكنات DLI، وإرسال الأموال مباشرة من المحادثة.',
    feat3_title: 'تمويل لامركزي وتخزين',
    feat3_desc: 'خزّن توكنات DLI للحصول على مكافآت USDT. فترات متعددة متاحة. الوصول إلى التطبيقات اللامركزية عبر متصفح الويب المدمج.',
    sec_start: 'كيف <span class="acc">تبدأ</span>',
    step1_title: 'حمّل التطبيق',
    step1_desc: 'متاح على <a href="https://apps.apple.com/us/app/dlicom/id6502626332" target="_blank">متجر التطبيقات</a> و<a href="https://play.google.com/store/search?q=dlicom&c=apps" target="_blank">جوجل بلاي</a>. المطور: Shlenpower Pte. Ltd.',
    step2_title: 'أنشئ محفظة',
    step2_desc: 'أثناء التسجيل، أنشئ محفظة جديدة أو استورد محفظة موجودة. احفظ عبارة الاسترداد في مكان آمن — الاسترداد دونها مستحيل.',
    step3_title: 'انضم إلى ديسكورد',
    step3_desc: 'انضم إلى <a href="https://discord.gg/BmYmRXc8" target="_blank">السيرفر الرسمي</a>. اختر منطقتك للوصول إلى القنوات المناسبة.',
    step4_title: 'كن عضوًا نشطًا',
    step4_desc: 'شارك في الأنشطة، ساعد الأعضاء الجدد، وانضم إلى صيد المنطقة — واحصل على أدوار Dliever وDcoded وDCO.',
    sec_hunt: 'صيد <span class="acc">قائد المنطقة</span>',
    hunt_title: 'كن قائد منطقة أو مشرفًا',
    hunt_desc: 'لحظة يستطيع فيها أي شخص أن يصبح قائدًا لمنطقته. اعمل مع الفريق، احصل على الأدوار وشكّل المجتمع. الآن — لا مشرفين ولا قادة. المكان شاغر.',
    hunt_apply: 'قدّم طلبك الآن',
    hunt_discord: 'اذهب إلى ديسكورد',
    hrole1_desc: 'مدير مجتمع منطقتك. مسؤول عن النمو والاستبقاء والتموضع وإدارة حملات المنطقة والتحليلات.',
    hrole2_desc: 'مساعد القائد. يجيب على الأسئلة، يرشد الأعضاء، ينظم الفعاليات ويحافظ على نشاط المحادثة.',
    hrole3_desc: 'منشئو المحتوى والمساهمون النشطون. يبنون الألعاب والمواقع ويساعدون الفريق. نشطون بشكل رئيسي في <strong>#creators</strong> و<strong>#dlicom-creators</strong>.',
    hrole4_tag: '🔹 صياد مبتدئ',
    hrole4_desc: 'امل الاستمارة واحصل على هذا الدور الخاص — يمنح وصولًا إلى <strong>#nominations</strong> وقنوات خاصة أخرى.',
    hrole4_link: 'اشترك في الاستمارة ←',
    sec_phases: 'مراحل <span class="acc">الصيد</span>',
    phase1_label: 'المرحلة الأولى',
    phase1_title: 'أثبت وجودك',
    phase1_dates: '٢٧ فبراير — ١١ مارس',
    phase1_desc: 'الاختيار الأولي. تفتح قناة الترشيحات. يراقب الفريق ويساعد ويرشد الجميع في الاتجاه الصحيح.',
    phase1_li1: '١٠ أدوار Dliever لكل منطقة',
    phase1_li2: 'الترشيحات مفتوحة لمن ملأوا الاستمارة',
    phase1_li3: 'دور الصياد المبتدئ متاح',
    phase2_label: 'المرحلة الثانية',
    phase2_title: 'فترة التجربة',
    phase2_dates: '١٢ مارس — ١٩ مارس',
    phase2_desc: 'أفضل ٥ مرشحين لكل منطقة يبدأون العمل مع فريق المجتمع. يمكن للمرشحين المختارين ترشيح أشخاص لـ Dliever وDcoded.',
    phase2_li1: '٥ أدوار Dcoded لكل منطقة',
    phase2_li2: 'Dliever فقط يمكنه الحصول على Dcoded',
    phase2_li3: 'تعاون مباشر مع الفريق',
    phase3_label: 'المرحلة الثالثة',
    phase3_title: 'النهائي',
    phase3_dates: '٢٠ مارس — ٢٧ مارس',
    phase3_desc: 'يتم تعيين القادة والمشرفين وتوزيع الأدوار والصلاحيات. يصبح الدور الأصعب — ضابط مساهمة Dlicom — متاحًا.',
    phase3_li1: 'دور DCO واحد لكل منطقة',
    phase3_li2: 'يجب امتلاك Dcoded + شارة سيرفر Dlicom',
    phase3_li3: 'تعيين قائد ومساعد المنطقة',
    results_title: 'النتائج لكل منطقة',
    res_p1: '(المرحلة الأولى)',
    res_p2: '(المرحلة الثانية)',
    res_p3: '(المرحلة الثالثة)',
    sec_roles: 'أدوار <span class="acc">المجتمع</span>',
    role1_desc: 'رواد أثبتوا موثوقيتهم ومعرفتهم بـ Dlicom. الدور الأساسي الأكثر طلبًا — بداية كل شيء.',
    role2_desc: 'أعضاء نشطون ومتفانون — قدوة للأعضاء الجدد. يتطلب دور Dliever.',
    role3_desc: 'ضابط مساهمة Dlicom. الدور الأندر. يتطلب Dcoded + شارة السيرفر.',
    role4_desc: 'أول ألف مستخدم أسطوريين. تعزيز إيردروب ونقاط تجربة إضافية. لم يعد يُمنح.',
    sec_rules: 'قواعد <span class="acc">المجتمع</span>',
    rule1_title: 'محظور',
    rule1_desc: 'السياسة والعنصرية والتمييز. المحتوى غير اللائق. البريد العشوائي والترويج الذاتي. المواضيع الخارجة عن القنوات المخصصة.',
    rule2_title: 'مرحبًا به',
    rule2_desc: 'ساعد الأعضاء الجدد، طوّر نفسك، ابنِ علاقات. حوّل الأفكار إلى أفعال. كن نفسك.',
    rule3_title: 'احذر من الاحتيال',
    rule3_desc: 'فريق Dlicom <strong>لن يراسلك أبدًا أولًا في الرسائل الخاصة</strong>. تحقق دائمًا.',
    rule4_title: 'مبدأ المجتمع',
    rule4_desc: 'القيمة هي كل شيء. قناة <strong>#creators</strong> هي أكثر الطرق موثوقية للحصول على دور.',
    sec_token: 'توكينو<span class="acc">ميكس</span>',
    leg1: 'بيع الشبكة',
    leg2: 'البيع المسبق العام',
    leg3: 'السيولة',
    leg4: 'البيع العام',
    leg5: 'الخزانة والاحتياطي',
    leg6: 'النظام البيئي / المصروفات',
    leg7: 'المؤسسون والفريق',
    leg8: 'المجتمع / حوافز المستخدمين',
    leg9: 'الاستشاريون',
    sec_tokdet: 'تفاصيل التوكن <span class="acc">$DLI</span>',
    tok_standard: 'المعيار',
    tok_supply: 'إجمالي المعروض',
    tok_price: 'السعر الابتدائي',
    tok_circ: 'التداول الابتدائي',
    tok_cap: 'القيمة السوقية الابتدائية',
    tok_lp: 'مجمع السيولة',
    tok_vest: 'جدول الاستحقاق',
    tok_vest_val: '٠–٦٠ شهرًا',
    tok_dec: 'الكسور العشرية',
    sec_team: 'فريق <span class="acc">Dlicom</span>',
    team1_role: 'رئيس مجلس الإدارة والمؤسس المشارك',
    team2_role: 'رئيس قسم التوكينوميكس',
    team3_role: 'مدير المجتمع',
    team4_role: 'مدير المنتج',
    sec_faq: 'الأسئلة <span class="acc">الشائعة</span>',
    faq0_q: 'ما هو دور الصياد المبتدئ؟',
    faq0_a: 'امل <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">استمارة الطلب</a> واحصل على دور الصياد المبتدئ — يمنح وصولًا إلى <strong>#nominations</strong> وقنوات خاصة أخرى خلال فترة الصيد.',
    faqA_q: 'ما الفرق بين قائد المنطقة ومساعد المنطقة؟',
    faqA_a: '<strong>قائد المنطقة</strong> هو مدير مجتمع المنطقة: النمو والاستبقاء والحملات والتحليلات. <strong>مساعد المنطقة</strong> هو معاون القائد: يجيب على الأسئلة، يرشد الأعضاء، ينظم الفعاليات، يحافظ على نشاط المحادثة.',
    faq1_q: 'كيف تصبح قائد منطقة؟',
    faq1_a: '١. امل <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">استمارة الطلب</a>. ٢. في ديسكورد، اختر منطقتك. ٣. شارك بفاعلية في المراحل الثلاث (٢٧ فبراير — ٢٧ مارس).',
    faq2_q: 'هل دور Dliever مطلوب للانضمام إلى صيد المنطقة؟',
    faq2_a: 'لا. Dliever غير مطلوب للتقديم. لكن المشاركين النشطين يحصلون عليه تلقائيًا ولهم الأولوية في الاختيار.',
    faq3_q: 'ما هو توكن DLI؟',
    faq3_a: 'DLI هو التوكن الأصلي لـ Dlicom على شبكة Ethereum. يُستخدم لـ: إرسال العملات المشفرة في المحادثة، الإكراميات، دفع رسوم الغاز، التخزين مع مكافآت USDT، والتصويت.',
    faq4_q: 'هل التحقق من الهوية مطلوب؟',
    faq4_a: 'لا. Dlicom مشروع لامركزي بالكامل يعمل كبورصة لامركزية. لا يُشترط التحقق من الهوية. الملفات الشخصية مبنية على عناوين Ethereum.',
    faq5_q: 'ما هو مسابقة شخصية Dili؟',
    faq5_a: 'أنشئ قصة أو عالمًا خياليًا أو مفهومًا عن Dili (نص، فيديو، فن). أفضل ١٠ أفكار تحصل على دور Dliever. انشر في <code>#creators</code> مع اقتباس <a href="https://x.com/DlicomApp/status/2023744462434783676" target="_blank">منشور إكس</a>.',
    faq6_q: 'كيف تكسب على المنصة؟',
    faq6_a: '<code>التخزين</code> — DLI مقابل مكافآت USDT. <code>المحتوى</code> — إكراميات من المتابعين. <code>الإحالات</code> — ادعُ أصدقاءك بكودك الخاص.',
    faq7_q: 'هل يمكنني التقدم لقائد المنطقة مباشرة دون المرور بالمساعد؟',
    faq7_a: 'نعم. بتقديم طلبك لقائد المنطقة، تصبح تلقائيًا مرشحًا لمساعد المنطقة أيضًا.',
    faq8_q: 'لماذا الآن هو أفضل وقت للانضمام؟',
    faq8_a: 'هذه المرحلة الأولى — لا يوجد مشرفون ولا قادة في المناطق بعد. البدء من الصفر الآن هو أفضل فرصة لتصبح قائد منطقة أو مساعدًا.',
    sec_links: 'الروابط <span class="acc">الرسمية</span>',
    link_wp: 'الورقة البيضاء',
    link_tgoff: 'تيليغرام الرسمي',
    link_tgcis: 'تيليغرام رابطة الدول المستقلة',
    link_yt: 'يوتيوب',
    link_med: 'مدونة Medium',
    sec_news: 'تحديثات <span class="acc">ديسكورد</span>',
    news1_date: '٢ مارس ٢٠٢٥',
    news_badge_new: 'جديد',
    news1_title: '📌 #content-spotlight — اختيار الغارة',
    news1_body: 'ظهرت قناة جديدة <strong>#content-spotlight</strong> في ديسكورد — عرض مخصص لأفضل محتوى المجتمع. سيختار المشرفون يدويًا منشورات المبدعين ويعرضونها هناك، ثم ينظمون غارة كاملة على أفضل الأعمال. إذا وصل منشورك إلى <strong>#content-spotlight</strong>، يعتبره الفريق جديرًا بأقصى انتشار. هذه فرصتك للتميز بين مئات المشاركين وإلفات نظر الفريق. انشر واجتهد — وقد تكون الغارة القادمة عليك.',
    news_tag_announce: '📣 إعلان',
    news2_date: '٢٧ فبراير ٢٠٢٥',
    news_badge_phase1: 'المرحلة الأولى',
    news2_title: '🚀 انطلاق صيد المنطقة',
    news2_body: 'طلبات قائد المنطقة ومساعد المنطقة مفتوحة رسميًا الآن. قناة <strong>#nominations</strong> مفتوحة لحاملي دور الصياد المبتدئ. قدّم طلبك الآن وكن من الأوائل.',
    news_tag_hunt: '🏹 الصيد',
    news3_date: 'فبراير ٢٠٢٥',
    news_badge_info: 'معلومات',
    news3_title: '🎭 مسابقة قصة Dili',
    news3_body: 'أنشئ قصة أو فنًا أو مفهومًا عن شخصية Dili. أفضل ١٠ مشاركات تحصل تلقائيًا على دور <strong>Dliever</strong>. انشر في <code>#creators</code> مع اقتباس منشور إكس الرسمي.',
    news_tag_creators: '🎨 المبدعون',
    news4_date: '٥ مارس ٢٠٢٥',
    news4_title: '🛡️ تعيين مشرفين تجريبيين',
    news4_body: 'تم تعيين 6 مشرفين تجريبيين في سيرفر Discord. بعد فترة تجريبية مدتها أسبوعان، سيبقى اثنان منهم كمشرفين دائمين. عملية الاختيار جارية — الأفضل سيبقى.',
    news_tag_mod: '🛡️ الإشراف',
    cta_title: 'هل أنت مستعد للانضمام إلى مركز المجتمع؟',
    cta_desc: 'انضم إلى ديسكورد، اختر منطقتك وشارك في صيد المنطقة',
    cta_btn1: '↗ افتح ديسكورد',
    cta_btn2: 'قدّم طلبك الآن',
    footer_brand: 'مركز المجتمع · مصدر غير رسمي',
    footer_apply: 'استمارة الطلب',
    footer_discord: '',
    footer_discord_txt: 'انضم إلى السيرفر',
    nav_tg_news: 'أخبار TG',
    tg_post_title: '<strong>الصيد الإقليمي: المرحلة التالية ستكون في 11 مارس! 🗺️</strong>',
    tg_post_body: 'الموسم 1 ينتهي اليوم في 00:00 UTC لروسيا وأوكرانيا ونيجيريا وفيتنام والمنطقة العربية والهند. إذا كنت منشئ محتوى أو مساهماً أو منشئ مجتمع — الوقت الآن!',
    tg_news_open: 'فتح Discord',
    tg_post_form: '👉 Discord Dlicom',
    news10_date: '10 مارس 2025',
    news10_title: '🗺️ الصيد الإقليمي: المرحلة التالية ستكون في 11 مارس!',
    news10_body: 'الموسم 1 ينتهي اليوم في 00:00 UTC لروسيا وأوكرانيا ونيجيريا وفيتنام والمنطقة العربية والهند. إذا كنت منشئ محتوى أو مساهماً أو منشئ مجتمع — الوقت الآن!',
    news10_btn: 'Discord Dlicom →',
    news7_date: '8 مارس 2025',
    news7_title: '🎯 المرحلة 1 تنتهي — كيف تعمل الأدوار',
    news7_body: 'في 11 مارس تنتهي المرحلة 1. سيتم اختيار ~60 <strong>Dliever</strong> و~30 مكان تجريبي. <strong>Regional Lead</strong> — وجه منطقتك والنمو وإدارة المجتمع. <strong>Regional Helper (Mod)</strong> — الترجمة والفعاليات والإشراف. <strong>Dliever وأدوار أخرى</strong> — إنشاء المحتوى في <code>#creators</code>.',
    news7_btn: 'املأ النموذج →',
    news8_date: '8 مارس 2025',
    news8_title: '📺 تسليط الضوء الأسبوعي — بث مباشر',
    news8_body: '8 مارس الساعة 19:00 — الفريق يبث مباشرة لمراجعة أفضل أعمال المجتمع وتقديم ملاحظات حقيقية. <a href="https://docs.google.com/forms/d/e/1FAlpQLSc1cJCwTX-bJc1R41CMucUuTGMrYdlqjQXq03aoArXEz3cyyg/viewform" target="_blank">أرسل عملك</a>.',
    news9_date: '7 مارس 2025',
    news9_title: '💼 توظيف: زميل SMM بدوام جزئي',
    news9_body: 'Dlicom يبحث عن متخصص SMM بدوام جزئي. يجب أن تكون مرتاحاً في Web3 وتتابع الاتجاهات وتنشئ محتوى أصلي لـ X وTelegram. الموعد النهائي: 20 مارس. <a href="https://forms.gle/qvBF4vKm8ynGPD618" target="_blank">تقدم هنا</a>.',
    news_tag_team: '💼 الفريق',
  },

  uk: {
    nav_sub: 'Хаб спільноти',
    nav_about: 'Про нас',
    nav_hunt: 'Хант',
    nav_roles: 'Ролі',
    nav_token: 'Токен',
    nav_team: 'Команда',
    nav_news: 'Новини',
    nav_discord: '↗ Discord',
    hero_tag: '🌍 Глобальна спільнота',
    hero_sub: 'Все про <strong>Dlicom</strong> — децентралізовану платформу з DeFi, крипто-гаманцем і соціальною мережею. Гайди, FAQ і новини для глобальної спільноти.',
    hero_btn1: '↗ Увійти в Discord',
    hero_btn2: 'Сайт проєкту',
    scroll: 'скрол',
    stat_token: 'Токен',
    stat_platform: 'Платформа',
    stat_supply: 'Загальний запас',
    stat_standard: 'Стандарт',
    mascot_title: 'Знайомтесь — Діли',
    mascot_desc: 'Офіційний маскот Dlicom — обличчя SocialFi. Створи історію, лор або концепт про нього та отримай роль <strong>Dliever</strong>. Будь-який формат: текст, відео, арт.',
    mascot_btn: 'Брендинг →',
    sec_what: 'Що таке <span class="acc">Dlicom</span>',
    feat1_title: 'Соціальна мережа',
    feat1_desc: 'Публікуй пости, спілкуйся в зашифрованих повідомленнях, отримуй чайові в токенах DLI. Альтернатива традиційним соцмережам без цензури.',
    feat2_title: 'Крипто-гаманець',
    feat2_desc: 'Self-custody гаманець з підтримкою крипти та NFT. Свопи за найкращим курсом, оплата газу токенами DLI, надсилання прямо в чаті.',
    feat3_title: 'DeFi і Стейкінг',
    feat3_desc: 'Стейкінг DLI токенів за винагороди в USDT. Кілька періодів. Доступ до dApps через вбудований Web3 браузер.',
    sec_start: 'Як <span class="acc">почати</span>',
    step1_title: 'Завантаж додаток',
    step1_desc: 'Доступний в <a href="https://apps.apple.com/us/app/dlicom/id6502626332" target="_blank">App Store</a> та <a href="https://play.google.com/store/search?q=dlicom&c=apps" target="_blank">Google Play</a>. Розробник: Shlenpower Pte. Ltd.',
    step2_title: 'Створи гаманець',
    step2_desc: 'Під час реєстрації створи новий гаманець або імпортуй існуючий. Збережи сід-фразу в безпечному місці — відновлення без неї неможливе.',
    step3_title: 'Увійди в Discord',
    step3_desc: 'Приєднайся до <a href="https://discord.gg/BmYmRXc8" target="_blank">офіційного сервера</a>. Обери свій регіон для доступу до потрібних каналів.',
    step4_title: 'Стань активним учасником',
    step4_desc: 'Бери участь в активностях, допомагай новачкам, приєднуйся до Regional Hunt — отримуй ролі Dliever, Dcoded і DCO.',
    sec_hunt: 'Хант на <span class="acc">регіонального ліда</span>',
    hunt_title: 'Стань Regional Lead або Модератором',
    hunt_desc: 'Момент, коли кожен може стати лідером свого регіону. Працюй з командою, отримуй ролі та формуй спільноту. Прямо зараз — немає модераторів, немає лідів. Місце вільне.',
    hunt_apply: 'Подати заявку',
    hunt_discord: 'Перейти в Discord',
    hrole1_desc: 'Менеджер спільноти свого регіону. Відповідає за зростання, утримання, позиціонування, управління регіональними кампаніями та аналітику.',
    hrole2_desc: "Помічник лідера. Відповідає на запитання, допомагає учасникам, проводить івенти та підтримує активність у чаті.",
    hrole3_desc: 'Активні творці контенту та контрибʼютори. Роблять ігри, сайти, допомагають команді. Переважно активні в <strong>#creators</strong> та <strong>#dlicom-creators</strong>.',
    hrole4_tag: '🔹 Молодший мисливець',
    hrole4_desc: 'Заповни форму та отримай цю особливу роль — вона надає доступ до <strong>#nominations</strong> та інших приватних каналів.',
    hrole4_link: 'Заповнити форму →',
    sec_phases: 'Фази <span class="acc">ханту</span>',
    phase1_label: 'Фаза 1',
    phase1_title: 'Заяви про себе',
    phase1_dates: '27 ЛЮТ — 11 БЕР',
    phase1_desc: 'Початковий відбір. Відкривається канал номінацій. Команда спостерігає, допомагає та направляє всіх у потрібному напрямку.',
    phase1_li1: '10 ролей Dliever на регіон',
    phase1_li2: 'Номінації відкриті для тих, хто заповнив форму',
    phase1_li3: 'Роль Молодшого мисливця доступна',
    phase2_label: 'Фаза 2',
    phase2_title: 'Випробувальний період',
    phase2_dates: '12 БЕР — 19 БЕР',
    phase2_desc: 'Топ-5 кандидатів по регіонах починають роботу з командою спільноти. Відібрані кандидати можуть номінувати людей на Dliever і Dcoded.',
    phase2_li1: '5 ролей Dcoded на регіон',
    phase2_li2: 'Тільки Dliever може отримати Dcoded',
    phase2_li3: 'Пряма взаємодія з командою',
    phase3_label: 'Фаза 3',
    phase3_title: 'Фінал',
    phase3_dates: '20 БЕР — 27 БЕР',
    phase3_desc: 'Ліди та модератори призначені, ролі та права видані. Стає доступна найважча роль — Dlicom Contribution Officer.',
    phase3_li1: '1 роль DCO на регіон',
    phase3_li2: 'Потрібні Dcoded + тег сервера Dlicom',
    phase3_li3: 'Призначені Regional Lead і Helper',
    results_title: 'Результати на регіон',
    res_p1: '(Фаза 1)',
    res_p2: '(Фаза 2)',
    res_p3: '(Фаза 3)',
    sec_roles: 'Ролі <span class="acc">спільноти</span>',
    role1_desc: 'Першопрохідці, які довели свою надійність і знання Dlicom. Найбажаніша базова роль — початок усього.',
    role2_desc: 'Активні та відданні учасники — приклад для новачків. Вимагає роль Dliever.',
    role3_desc: 'Dlicom Contribution Officer. Найрідкісніша роль. Вимагає Dcoded + тег сервера.',
    role4_desc: 'Легендарні перші 1000 користувачів. Буст аірдропу, бонусний XP. Більше не видається.',
    sec_rules: 'Правила <span class="acc">спільноти</span>',
    rule1_title: 'Заборонено',
    rule1_desc: 'Політика, расизм, дискримінація. Контент для дорослих. Спам і самореклама. Офтопік у тематичних каналах.',
    rule2_title: 'Вітається',
    rule2_desc: "Допомагай новачкам, розвивайся сам, будуй зв'язки. Перетворюй ідеї на дії. Будь собою.",
    rule3_title: 'Обережно: скамери',
    rule3_desc: 'Команда Dlicom <strong>ніколи не напише тобі першою в особисті повідомлення</strong>. Завжди перевіряй.',
    rule4_title: 'Принцип спільноти',
    rule4_desc: 'Цінність — це все. Канал <strong>#creators</strong> — найнадійніший спосіб отримати роль.',
    sec_token: 'Токено<span class="acc">міка</span>',
    leg1: 'Мережевий продаж',
    leg2: 'Публічний пресейл',
    leg3: 'Ліквідність',
    leg4: 'Публічний продаж',
    leg5: 'Казначейство та резерв',
    leg6: 'Екосистема / Витрати',
    leg7: 'Засновники та команда',
    leg8: 'Спільнота / Стимули користувачів',
    leg9: 'Консультанти',
    sec_tokdet: 'Деталі токена <span class="acc">$DLI</span>',
    tok_standard: 'Стандарт',
    tok_supply: 'Загальний запас',
    tok_price: 'Початкова ціна',
    tok_circ: 'Початковий обіг',
    tok_cap: 'Початкова ринкова кап.',
    tok_lp: 'Пул ліквідності',
    tok_vest: 'Вестинг',
    tok_vest_val: '0–60 місяців',
    tok_dec: 'Десяткові знаки',
    sec_team: 'Команда <span class="acc">Dlicom</span>',
    team1_role: 'Голова та співзасновник',
    team2_role: 'Керівник відділу токеноміки',
    team3_role: 'Менеджер спільноти',
    team4_role: 'Менеджер продукту',
    sec_faq: 'Часті <span class="acc">запитання</span>',
    faq0_q: 'Що таке роль «Молодший мисливець»?',
    faq0_a: 'Заповни <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">форму заявки</a> та отримай роль Молодшого мисливця — вона надає доступ до <strong>#nominations</strong> та інших приватних каналів під час Ханту.',
    faqA_q: 'У чому різниця між Regional Lead і Regional Helper?',
    faqA_a: '<strong>Regional Lead</strong> — менеджер спільноти свого регіону: зростання, утримання, кампанії, аналітика. <strong>Regional Helper</strong> — помічник лідера: відповідає на запитання, допомагає учасникам, проводить івенти, підтримує активність у чаті.',
    faq1_q: 'Як стати Regional Lead?',
    faq1_a: '1. Заповни <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">форму заявки</a>. 2. В Discord обери свій регіон. 3. Активно бери участь у всіх трьох фазах (27 лют — 27 бер).',
    faq2_q: 'Чи потрібна роль Dliever для участі в Regional Hunt?',
    faq2_a: 'Ні. Dliever не є обовʼязковим для подачі заявки. Але активні учасники отримують її автоматично та мають пріоритет при відборі.',
    faq3_q: 'Що таке токен DLI?',
    faq3_a: 'DLI — нативний токен Dlicom на Ethereum. Використовується для: надсилання крипти у чаті, чайових, оплати газу, стейкінгу з USDT-нагородами та голосування.',
    faq4_q: 'Чи потрібен KYC?',
    faq4_a: 'Ні. Dlicom — повністю децентралізований проєкт, що працює як DEX. KYC не потрібен. Профілі базуються на адресах Ethereum.',
    faq5_q: 'Що таке конкурс маскота Діли?',
    faq5_a: 'Створи історію, лор або концепт про Діли (текст, відео, арт). Найкращі 10 ідей отримують роль Dliever. Публікуй у <code>#creators</code>, цитуючи <a href="https://x.com/DlicomApp/status/2023744462434783676" target="_blank">X пост</a>.',
    faq6_q: 'Як заробляти на платформі?',
    faq6_a: '<code>Стейкінг</code> — DLI за USDT-нагороди. <code>Контент</code> — чайові від підписників. <code>Реферали</code> — запрошуй за своїм кодом.',
    faq7_q: 'Чи можна подати заявку відразу на Regional Lead, оминаючи Helper?',
    faq7_a: 'Так. Подаючи заявку на Regional Lead, ти автоматично стаєш кандидатом і на Regional Helper.',
    faq8_q: 'Чому зараз найкращий час для вступу?',
    faq8_a: 'Це найраніший етап — у регіонах поки немає модераторів і лідів. Почати з нуля прямо зараз — найкраще вікно, щоб стати Regional Lead або Helper.',
    sec_links: 'Офіційні <span class="acc">посилання</span>',
    link_wp: 'Вайтпейпер',
    link_tgoff: 'Telegram Офіційний',
    link_tgcis: 'Telegram СНД',
    link_yt: 'YouTube',
    link_med: 'Блог на Medium',
    sec_news: 'Оновлення <span class="acc">Discord</span>',
    news1_date: '2 БЕР 2025',
    news_badge_new: 'НОВЕ',
    news1_title: '📌 #content-spotlight — рейд-вибірка',
    news1_body: "У Discord з'явився новий канал <strong>#content-spotlight</strong> — вітрина найкращого контенту спільноти. Модератори будуть відбирати пости творців і публікувати їх там, а потім організовувати повноцінний рейд на топові роботи. Якщо твій пост потрапить у <strong>#content-spotlight</strong>, команда вважає його гідним максимального охоплення. Це твій шанс виділитися серед сотень учасників Ханту та потрапити в поле зору команди. Публікуй, старайся — і наступний рейд може бути на тебе.",
    news_tag_announce: '📣 Оголошення',
    news2_date: '27 ЛЮТ 2025',
    news_badge_phase1: 'ФАЗА 1',
    news2_title: '🚀 Regional Hunt запущено',
    news2_body: 'Заявки на Regional Lead та Regional Helper офіційно відкриті. Канал <strong>#nominations</strong> розблоковано для власників ролі Молодшого мисливця. Подавай заявку зараз і будь серед перших.',
    news_tag_hunt: '🏹 Хант',
    news3_date: 'ЛЮТ 2025',
    news_badge_info: 'ІНФО',
    news3_title: '🎭 Конкурс лору Діли',
    news3_body: 'Створи історію, арт або концепт про маскота Діли. Найкращі 10 робіт автоматично отримують роль <strong>Dliever</strong>. Публікуй у <code>#creators</code>, цитуючи офіційний X пост.',
    news_tag_creators: '🎨 Творці',
    news4_date: '5 БЕР 2025',
    news4_title: '🛡️ Призначено тестових модераторів',
    news4_body: 'На сервері Discord призначено 6 тестових модераторів. Після двотижневого випробувального періоду з них залишаться 2 постійних модератори. Відбір триває — кращі залишаться.',
    news_tag_mod: '🛡️ Модерація',
    news5_date: '5 БЕР 2025',
    news5_title: '🏆 Турнір з CS2 — регіон СНД',
    news5_body: '5 березня о 19:00 за МСК відбудеться турнір з CS2 в регіоні СНД. Подати заявку на участь можна за посиланням нижче.',
    news5_btn: '📋 Подати заявку',
    news_tag_tournament: '🏆 Турнір',
    cta_title: 'Готовий приєднатися до Community Hub?',
    cta_desc: 'Увійди в Discord, обери регіон та бери участь у Regional Hunt',
    cta_btn1: '↗ Відкрити Discord',
    cta_btn2: 'Подати заявку',
    footer_brand: 'Community Hub · Неофіційний ресурс',
    footer_apply: 'Форма заявки',
    footer_discord: '',
    footer_discord_txt: 'Увійти на сервер',
    nav_tg_news: 'TG НОВИНИ',
    tg_post_title: '<strong>Regional Hunt: наступний етап — 11 березня! 🗺️</strong>',
    tg_post_body: 'Сезон 1 закінчується сьогодні о 00:00 UTC для Росії, України, Нігерії, В\'єтнаму, арабського регіону та Індії. Якщо ти творець, контрибьютор або будівник спільноти — зараз твій час!',
    tg_news_open: 'Відкрити Discord',
    tg_post_form: '👉 Discord Dlicom',
    news10_date: '10 БЕР 2025',
    news10_title: '🗺️ Regional Hunt: наступний етап — 11 березня!',
    news10_body: 'Сезон 1 закінчується сьогодні о 00:00 UTC для Росії, України, Нігерії, В\'єтнаму, арабського регіону та Індії. Якщо ти творець, контрибьютор або будівник спільноти — зараз твій час!',
    news10_btn: 'Discord Dlicom →',
    news7_date: '8 БЕР 2025',
    news7_title: '🎯 Фаза 1 завершується — як працюють ролі',
    news7_body: '11 березня завершується Фаза 1. Буде обрано ~60 <strong>Dliever</strong> і ~30 місць на випробувальний термін. <strong>Regional Lead</strong> — обличчя регіону, зростання та управління спільнотою. <strong>Regional Helper (Mod)</strong> — переклади, івенти, модерація. <strong>Dliever та інші ролі</strong> — створення контенту в <code>#creators</code>.',
    news7_btn: 'Заповнити форму →',
    news8_date: '8 БЕР 2025',
    news8_title: '📺 Щотижневий Community Spotlight — прямий ефір',
    news8_body: '8 березня о 19:00 — команда виходить у прямий ефір для огляду кращих робіт спільноти та зворотного зв\'язку. <a href="https://docs.google.com/forms/d/e/1FAlpQLSc1cJCwTX-bJc1R41CMucUuTGMrYdlqjQXq03aoArXEz3cyyg/viewform" target="_blank">Надіслати роботу</a>.',
    news9_date: '7 БЕР 2025',
    news9_title: '💼 Вакансія: SMM-спеціаліст (part-time)',
    news9_body: 'Dlicom шукає SMM-спеціаліста на part-time. Потрібно розбиратися в Web3, стежити за трендами та створювати нативний контент для X і Telegram. Дедлайн: 20 березня. <a href="https://forms.gle/qvBF4vKm8ynGPD618" target="_blank">Подати заявку</a>.',
    news_tag_team: '💼 Команда',
  },

  vi: {
    nav_sub: 'Trung tâm Cộng đồng',
    nav_about: 'Giới thiệu',
    nav_hunt: 'Săn tìm',
    nav_roles: 'Vai trò',
    nav_token: 'Token',
    nav_team: 'Đội ngũ',
    nav_news: 'Tin tức',
    nav_discord: '↗ Discord',
    hero_tag: '🌍 Cộng đồng Toàn cầu',
    hero_sub: 'Tất cả về <strong>Dlicom</strong> — nền tảng phi tập trung với DeFi, ví crypto và mạng xã hội. Hướng dẫn, FAQ và tin tức cho cộng đồng toàn cầu.',
    hero_btn1: '↗ Tham gia Discord',
    hero_btn2: 'Website Dự án',
    scroll: 'cuộn',
    stat_token: 'Token',
    stat_platform: 'Nền tảng',
    stat_supply: 'Tổng cung',
    stat_standard: 'Tiêu chuẩn',
    mascot_title: 'Gặp gỡ Dili',
    mascot_desc: 'Linh vật chính thức của Dlicom — gương mặt của SocialFi. Tạo câu chuyện, truyền thuyết hoặc ý tưởng về anh ấy để nhận vai <strong>Dliever</strong>. Mọi định dạng: văn bản, video, nghệ thuật.',
    mascot_btn: 'Nhận dạng thương hiệu →',
    sec_what: 'Dlicom là <span class="acc">gì</span>',
    feat1_title: 'Mạng xã hội',
    feat1_desc: 'Đăng bài, trò chuyện qua tin nhắn mã hóa, kiếm tiền thưởng bằng token DLI. Thay thế chống kiểm duyệt cho mạng xã hội truyền thống.',
    feat2_title: 'Ví Crypto',
    feat2_desc: 'Ví tự quản lý hỗ trợ crypto và NFT. Hoán đổi tỷ giá tốt nhất, trả phí gas bằng token DLI, gửi trực tiếp trong chat.',
    feat3_title: 'DeFi & Đặt cọc',
    feat3_desc: 'Đặt cọc token DLI để nhận phần thưởng USDT. Nhiều kỳ hạn. Truy cập dApps qua trình duyệt Web3 tích hợp.',
    sec_start: 'Cách <span class="acc">bắt đầu</span>',
    step1_title: 'Tải ứng dụng',
    step1_desc: 'Có trên <a href="https://apps.apple.com/us/app/dlicom/id6502626332" target="_blank">App Store</a> và <a href="https://play.google.com/store/search?q=dlicom&c=apps" target="_blank">Google Play</a>. Nhà phát triển: Shlenpower Pte. Ltd.',
    step2_title: 'Tạo ví',
    step2_desc: 'Khi đăng ký, tạo ví mới hoặc nhập ví hiện có. Lưu cụm từ khôi phục ở nơi an toàn — không thể khôi phục nếu mất.',
    step3_title: 'Tham gia Discord',
    step3_desc: 'Tham gia <a href="https://discord.gg/BmYmRXc8" target="_blank">máy chủ chính thức</a>. Chọn khu vực của bạn để mở khóa các kênh phù hợp.',
    step4_title: 'Trở thành thành viên tích cực',
    step4_desc: 'Tham gia hoạt động, giúp đỡ người mới, tham gia Regional Hunt — nhận vai Dliever, Dcoded và DCO.',
    sec_hunt: '<span class="acc">Săn tìm</span> Trưởng vùng',
    hunt_title: 'Trở thành Trưởng vùng hoặc Mod',
    hunt_desc: 'Thời điểm bất kỳ ai cũng có thể trở thành lãnh đạo vùng của mình. Làm việc với nhóm, nhận vai và định hình cộng đồng. Ngay bây giờ — không có mod, không có lead. Vị trí đang trống.',
    hunt_apply: 'Đăng ký ngay',
    hunt_discord: 'Đến Discord',
    hrole1_desc: 'Quản lý cộng đồng vùng của bạn. Chịu trách nhiệm về tăng trưởng, giữ chân thành viên, định vị, quản lý chiến dịch vùng và phân tích.',
    hrole2_desc: 'Trợ lý của leader. Trả lời câu hỏi, hướng dẫn thành viên, tổ chức sự kiện và duy trì chat sôi động.',
    hrole3_desc: 'Nhà sáng tạo nội dung và cộng tác viên tích cực. Xây dựng game, website, hỗ trợ nhóm. Chủ yếu hoạt động trong <strong>#creators</strong> và <strong>#dlicom-creators</strong>.',
    hrole4_tag: '🔹 Thợ săn Sơ cấp',
    hrole4_desc: 'Điền form và nhận vai đặc biệt này — cho phép truy cập <strong>#nominations</strong> và các kênh riêng tư khác.',
    hrole4_link: 'Điền form →',
    sec_phases: 'Các giai đoạn <span class="acc">Săn tìm</span>',
    phase1_label: 'Giai đoạn 1',
    phase1_title: 'Tạo dấu ấn',
    phase1_dates: '27 Tháng 2 — 11 Tháng 3',
    phase1_desc: 'Vòng chọn lọc đầu tiên. Kênh đề cử mở. Nhóm quan sát, giúp đỡ và hướng dẫn mọi người đúng hướng.',
    phase1_li1: '10 vai Dliever mỗi vùng',
    phase1_li2: 'Đề cử mở cho người điền form',
    phase1_li3: 'Vai Thợ săn Sơ cấp có sẵn',
    phase2_label: 'Giai đoạn 2',
    phase2_title: 'Thời gian thử thách',
    phase2_dates: '12 Tháng 3 — 19 Tháng 3',
    phase2_desc: 'Top 5 ứng viên mỗi vùng bắt đầu làm việc với nhóm cộng đồng. Ứng viên được chọn có thể đề cử người cho Dliever và Dcoded.',
    phase2_li1: '5 vai Dcoded mỗi vùng',
    phase2_li2: 'Chỉ Dliever mới nhận được Dcoded',
    phase2_li3: 'Hợp tác trực tiếp với nhóm',
    phase3_label: 'Giai đoạn 3',
    phase3_title: 'Chung kết',
    phase3_dates: '20 Tháng 3 — 27 Tháng 3',
    phase3_desc: 'Lead và mod được bổ nhiệm, vai và quyền được phân công. Vai khó nhất — Dlicom Contribution Officer — trở nên khả dụng.',
    phase3_li1: '1 vai DCO mỗi vùng',
    phase3_li2: 'Cần có Dcoded + thẻ server Dlicom',
    phase3_li3: 'Bổ nhiệm Regional Lead & Helper',
    results_title: 'Kết quả mỗi vùng',
    res_p1: '(Giai đoạn 1)',
    res_p2: '(Giai đoạn 2)',
    res_p3: '(Giai đoạn 3)',
    sec_roles: 'Vai trò <span class="acc">Cộng đồng</span>',
    role1_desc: 'Những người tiên phong đã chứng minh độ tin cậy và kiến thức về Dlicom. Vai cơ sở được tìm kiếm nhiều nhất — khởi đầu của tất cả.',
    role2_desc: 'Thành viên tích cực và tận tâm — gương mẫu cho người mới. Yêu cầu vai Dliever.',
    role3_desc: 'Dlicom Contribution Officer. Vai hiếm nhất. Yêu cầu Dcoded + thẻ server.',
    role4_desc: '1000 người dùng đầu tiên huyền thoại. Boost airdrop, XP thưởng. Không còn được trao nữa.',
    sec_rules: 'Quy tắc <span class="acc">Cộng đồng</span>',
    rule1_title: 'Bị cấm',
    rule1_desc: 'Chính trị, phân biệt chủng tộc, phân biệt đối xử. Nội dung người lớn. Spam và tự quảng cáo. Lạc đề trong các kênh theo chủ đề.',
    rule2_title: 'Được chào đón',
    rule2_desc: 'Giúp đỡ người mới, phát triển bản thân, xây dựng kết nối. Biến ý tưởng thành hành động. Hãy là chính mình.',
    rule3_title: 'Cảnh giác lừa đảo',
    rule3_desc: 'Nhóm Dlicom sẽ <strong>không bao giờ nhắn tin trước trong DM</strong>. Luôn xác minh.',
    rule4_title: 'Nguyên tắc Cộng đồng',
    rule4_desc: 'Giá trị là tất cả. Kênh <strong>#creators</strong> là cách đáng tin cậy nhất để nhận vai.',
    sec_token: 'Tokeno<span class="acc">mics</span>',
    leg1: 'Bán mạng lưới',
    leg2: 'Bán trước công khai',
    leg3: 'Thanh khoản',
    leg4: 'Bán công khai',
    leg5: 'Kho bạc & Dự trữ',
    leg6: 'Hệ sinh thái / Chi phí',
    leg7: 'Nhà sáng lập & Nhóm',
    leg8: 'Cộng đồng / Ưu đãi người dùng',
    leg9: 'Cố vấn',
    sec_tokdet: 'Chi tiết Token <span class="acc">$DLI</span>',
    tok_standard: 'Tiêu chuẩn',
    tok_supply: 'Tổng cung',
    tok_price: 'Giá ban đầu',
    tok_circ: 'Lưu thông ban đầu',
    tok_cap: 'Vốn hóa thị trường ban đầu',
    tok_lp: 'Bể thanh khoản',
    tok_vest: 'Vesting',
    tok_vest_val: '0–60 tháng',
    tok_dec: 'Chữ số thập phân',
    sec_team: 'Đội ngũ <span class="acc">Dlicom</span>',
    team1_role: 'Chủ tịch & Đồng sáng lập',
    team2_role: 'Trưởng phòng Tokenomics',
    team3_role: 'Quản lý Cộng đồng',
    team4_role: 'Quản lý Sản phẩm',
    sec_faq: 'Câu hỏi <span class="acc">thường gặp</span>',
    faq0_q: 'Vai Thợ săn Sơ cấp là gì?',
    faq0_a: 'Điền <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">form đăng ký</a> và nhận vai Thợ săn Sơ cấp — cho phép truy cập <strong>#nominations</strong> và các kênh riêng tư khác trong Hunt.',
    faqA_q: 'Sự khác biệt giữa Regional Lead và Regional Helper là gì?',
    faqA_a: '<strong>Regional Lead</strong> là quản lý cộng đồng vùng: tăng trưởng, giữ chân, chiến dịch, phân tích. <strong>Regional Helper</strong> là trợ lý: trả lời câu hỏi, hướng dẫn thành viên, tổ chức sự kiện, duy trì chat.',
    faq1_q: 'Làm thế nào để trở thành Regional Lead?',
    faq1_a: '1. Điền <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">form đăng ký</a>. 2. Trong Discord, chọn vùng của bạn. 3. Tham gia tích cực trong cả ba giai đoạn (27 Feb — 27 Mar).',
    faq2_q: 'Có cần vai Dliever để tham gia Regional Hunt không?',
    faq2_a: 'Không. Dliever không bắt buộc để đăng ký. Nhưng người tham gia tích cực tự động nhận được và có ưu tiên trong tuyển chọn.',
    faq3_q: 'Token DLI là gì?',
    faq3_a: 'DLI là token bản địa của Dlicom trên Ethereum. Dùng để: gửi crypto trong chat, tiền tip, thanh toán phí gas, đặt cọc với phần thưởng USDT và bỏ phiếu.',
    faq4_q: 'Có cần KYC không?',
    faq4_a: 'Không. Dlicom là dự án phi tập trung hoàn toàn hoạt động như DEX. Không cần KYC. Hồ sơ dựa trên địa chỉ Ethereum.',
    faq5_q: 'Cuộc thi linh vật Dili là gì?',
    faq5_a: 'Tạo câu chuyện, nghệ thuật hoặc ý tưởng về Dili (văn bản, video, nghệ thuật). 10 ý tưởng hay nhất nhận vai Dliever. Đăng trong <code>#creators</code>, trích dẫn <a href="https://x.com/DlicomApp/status/2023744462434783676" target="_blank">bài đăng X</a>.',
    faq6_q: 'Làm thế nào để kiếm tiền trên nền tảng?',
    faq6_a: '<code>Đặt cọc</code> — DLI lấy phần thưởng USDT. <code>Nội dung</code> — tiền tip từ người theo dõi. <code>Giới thiệu</code> — mời qua mã của bạn.',
    faq7_q: 'Tôi có thể đăng ký Regional Lead trực tiếp không cần Helper không?',
    faq7_a: 'Có. Khi đăng ký Regional Lead, bạn tự động trở thành ứng viên Regional Helper.',
    faq8_q: 'Tại sao bây giờ là thời điểm tốt nhất để tham gia?',
    faq8_a: 'Đây là giai đoạn sớm nhất — chưa có mod, chưa có lead trong các vùng. Bắt đầu từ đầu ngay bây giờ là cơ hội tốt nhất để trở thành Regional Lead hoặc Helper.',
    sec_links: 'Liên kết <span class="acc">Chính thức</span>',
    link_wp: 'Sách trắng',
    link_tgoff: 'Telegram Chính thức',
    link_tgcis: 'Telegram CIS',
    link_yt: 'YouTube',
    link_med: 'Blog Medium',
    sec_news: 'Cập nhật <span class="acc">Discord</span>',
    news1_date: '2 THÁNG 3 2025',
    news_badge_new: 'MỚI',
    news1_title: '📌 #content-spotlight — chọn lọc raid',
    news1_body: 'Kênh mới <strong>#content-spotlight</strong> xuất hiện trong Discord — nơi trưng bày nội dung cộng đồng tốt nhất. Mod sẽ tay chọn bài đăng của creator và giới thiệu ở đó, sau đó tổ chức raid toàn diện vào các tác phẩm hàng đầu. Nếu bài đăng của bạn vào <strong>#content-spotlight</strong>, nhóm coi nó xứng đáng tiếp cận tối đa. Đây là cơ hội nổi bật giữa hàng trăm người tham gia Hunt. Đăng, cố gắng — và raid tiếp theo có thể là về bạn.',
    news_tag_announce: '📣 Thông báo',
    news2_date: '27 THÁNG 2 2025',
    news_badge_phase1: 'GIAI ĐOẠN 1',
    news2_title: '🚀 Regional Hunt ra mắt',
    news2_body: 'Đơn đăng ký Regional Lead và Regional Helper chính thức mở. Kênh <strong>#nominations</strong> mở khóa cho người có vai Thợ săn Sơ cấp. Đăng ký ngay và là người đầu tiên.',
    news_tag_hunt: '🏹 Săn tìm',
    news3_date: 'THÁNG 2 2025',
    news_badge_info: 'THÔNG TIN',
    news3_title: '🎭 Cuộc thi truyền thuyết Dili',
    news3_body: 'Tạo câu chuyện, nghệ thuật hoặc ý tưởng về linh vật Dili. 10 tác phẩm tốt nhất tự động nhận vai <strong>Dliever</strong>. Đăng trong <code>#creators</code> trích dẫn bài X chính thức.',
    news_tag_creators: '🎨 Nhà sáng tạo',
    news4_date: '5 THÁNG 3 2025',
    news4_title: '🛡️ Bổ nhiệm Mod thử nghiệm',
    news4_body: '6 mod thử nghiệm đã được bổ nhiệm trên Discord. Sau 2 tuần thử việc, 2 trong số họ sẽ ở lại làm mod chính thức. Quá trình chọn lọc đang diễn ra — người tốt nhất sẽ ở lại.',
    news_tag_mod: '🛡️ Kiểm duyệt',
    cta_title: 'Sẵn sàng tham gia Trung tâm Cộng đồng?',
    cta_desc: 'Tham gia Discord, chọn vùng của bạn và tham gia Regional Hunt',
    cta_btn1: '↗ Mở Discord',
    cta_btn2: 'Đăng ký ngay',
    footer_brand: 'Trung tâm Cộng đồng · Tài nguyên không chính thức',
    footer_apply: 'Mẫu đăng ký',
    footer_discord: '',
    footer_discord_txt: 'Tham gia Máy chủ',
    nav_tg_news: 'TIN TG',
    tg_post_title: '<strong>Regional Hunt: giai đoạn tiếp theo sẽ là ngày 11 tháng 3! 🗺️</strong>',
    tg_post_body: 'Mùa 1 kết thúc hôm nay lúc 00:00 UTC cho Nga, Ukraine, Nigeria, Việt Nam, khu vực Ả Rập và Ấn Độ. Nếu bạn là người tạo nội dung, cộng tác viên hoặc người xây dựng cộng đồng — đây là lúc của bạn!',
    tg_news_open: 'Mở Discord',
    tg_post_form: '👉 Discord Dlicom',
    news10_date: '10 TH3 2025',
    news10_title: '🗺️ Regional Hunt: giai đoạn tiếp theo sẽ là ngày 11 tháng 3!',
    news10_body: 'Mùa 1 kết thúc hôm nay lúc 00:00 UTC cho Nga, Ukraine, Nigeria, Việt Nam, khu vực Ả Rập và Ấn Độ. Nếu bạn là người tạo nội dung, cộng tác viên hoặc người xây dựng cộng đồng — đây là lúc của bạn!',
    news10_btn: 'Discord Dlicom →',
    news7_date: '8 TH3 2025',
    news7_title: '🎯 Giai đoạn 1 sắp kết thúc — Vai trò hoạt động thế nào',
    news7_body: 'Ngày 11/3, Giai đoạn 1 kết thúc. ~60 <strong>Dliever</strong> và ~30 suất thử việc sẽ được chọn. <strong>Regional Lead</strong> — đại diện khu vực, phát triển cộng đồng. <strong>Regional Helper (Mod)</strong> — dịch thuật, sự kiện, kiểm duyệt. <strong>Dliever & vai trò khác</strong> — sáng tạo nội dung trong <code>#creators</code>.',
    news7_btn: 'Điền đơn →',
    news8_date: '8 TH3 2025',
    news8_title: '📺 Community Spotlight hàng tuần — Phát trực tiếp',
    news8_body: 'Ngày 8/3 lúc 19:00 — đội ngũ phát trực tiếp đánh giá các tác phẩm tốt nhất và đưa phản hồi thực sự. <a href="https://docs.google.com/forms/d/e/1FAlpQLSc1cJCwTX-bJc1R41CMucUuTGMrYdlqjQXq03aoArXEz3cyyg/viewform" target="_blank">Gửi tác phẩm</a>.',
    news9_date: '7 TH3 2025',
    news9_title: '💼 Tuyển dụng: SMM bán thời gian',
    news9_body: 'Dlicom đang tìm thành viên SMM bán thời gian. Cần am hiểu Web3, theo dõi xu hướng và tạo nội dung cho X và Telegram. Hạn chót: 20/3. <a href="https://forms.gle/qvBF4vKm8ynGPD618" target="_blank">Ứng tuyển</a>.',
    news_tag_team: '💼 Nhóm',
  },

  hi: {
    nav_sub: 'कम्युनिटी हब',
    nav_about: 'परिचय',
    nav_hunt: 'हंट',
    nav_roles: 'भूमिकाएँ',
    nav_token: 'टोकन',
    nav_team: 'टीम',
    nav_news: 'समाचार',
    nav_discord: '↗ Discord',
    hero_tag: '🌍 वैश्विक समुदाय',
    hero_sub: '<strong>Dlicom</strong> के बारे में सब कुछ — DeFi, क्रिप्टो वॉलेट और सोशल नेटवर्क के साथ एक विकेंद्रीकृत प्लेटफ़ॉर्म। गाइड, FAQ और वैश्विक समुदाय के लिए समाचार।',
    hero_btn1: '↗ Discord से जुड़ें',
    hero_btn2: 'प्रोजेक्ट वेबसाइट',
    scroll: 'स्क्रॉल',
    stat_token: 'टोकन',
    stat_platform: 'प्लेटफ़ॉर्म',
    stat_supply: 'कुल आपूर्ति',
    stat_standard: 'मानक',
    mascot_title: 'Dili से मिलिए',
    mascot_desc: 'Dlicom का आधिकारिक शुभंकर — SocialFi का चेहरा। उसके बारे में एक कहानी, लोर या कॉन्सेप्ट बनाएँ और <strong>Dliever</strong> रोल पाएँ। कोई भी प्रारूप: टेक्स्ट, वीडियो, आर्ट।',
    mascot_btn: 'ब्रांडिंग →',
    sec_what: '<span class="acc">Dlicom</span> क्या है',
    feat1_title: 'सोशल नेटवर्क',
    feat1_desc: 'पोस्ट प्रकाशित करें, एन्क्रिप्टेड संदेशों में चैट करें, DLI टोकन में टिप्स कमाएँ। पारंपरिक सोशल नेटवर्क का सेंसरशिप-प्रतिरोधी विकल्प।',
    feat2_title: 'क्रिप्टो वॉलेट',
    feat2_desc: 'क्रिप्टो और NFT सपोर्ट के साथ सेल्फ-कस्टडी वॉलेट। सर्वोत्तम दर पर स्वैप, DLI टोकन से गैस फीस दें, सीधे चैट में भेजें।',
    feat3_title: 'DeFi और स्टेकिंग',
    feat3_desc: 'USDT पुरस्कारों के लिए DLI टोकन स्टेक करें। कई अवधियाँ उपलब्ध। अंतर्निहित Web3 ब्राउज़र के माध्यम से dApps एक्सेस करें।',
    sec_start: '<span class="acc">शुरू</span> कैसे करें',
    step1_title: 'ऐप डाउनलोड करें',
    step1_desc: '<a href="https://apps.apple.com/us/app/dlicom/id6502626332" target="_blank">App Store</a> और <a href="https://play.google.com/store/search?q=dlicom&c=apps" target="_blank">Google Play</a> पर उपलब्ध। डेवलपर: Shlenpower Pte. Ltd.',
    step2_title: 'वॉलेट बनाएँ',
    step2_desc: 'पंजीकरण के दौरान नया वॉलेट बनाएँ या मौजूदा इम्पोर्ट करें। सीड फ्रेज़ को सुरक्षित जगह सेव करें — इसके बिना रिकवरी असंभव है।',
    step3_title: 'Discord से जुड़ें',
    step3_desc: '<a href="https://discord.gg/BmYmRXc8" target="_blank">आधिकारिक सर्वर</a> से जुड़ें। सही चैनल अनलॉक करने के लिए अपना क्षेत्र चुनें।',
    step4_title: 'सक्रिय सदस्य बनें',
    step4_desc: 'गतिविधियों में भाग लें, नए लोगों की मदद करें, Regional Hunt से जुड़ें — Dliever, Dcoded और DCO रोल पाएँ।',
    sec_hunt: 'रीजनल लीड <span class="acc">हंट</span>',
    hunt_title: 'रीजनल लीड या मॉड बनें',
    hunt_desc: 'वह पल जब कोई भी अपने क्षेत्र का नेता बन सकता है। टीम के साथ काम करें, रोल पाएँ और समुदाय को आकार दें। अभी — कोई मॉडरेटर नहीं, कोई लीड नहीं। सीट खाली है।',
    hunt_apply: 'अभी आवेदन करें',
    hunt_discord: 'Discord पर जाएँ',
    hrole1_desc: 'अपने क्षेत्र के कम्युनिटी मैनेजर। विकास, रिटेंशन, पोजिशनिंग, रीजनल कैंपेन मैनेजमेंट और एनालिटिक्स के लिए जिम्मेदार।',
    hrole2_desc: "लीडर का सहायक। सवालों के जवाब देता है, सदस्यों को गाइड करता है, इवेंट चलाता है और चैट को सक्रिय रखता है।",
    hrole3_desc: 'सक्रिय कंटेंट क्रिएटर और कंट्रिब्यूटर। गेम, वेबसाइट बनाते हैं, टीम की मदद करते हैं। मुख्यतः <strong>#creators</strong> और <strong>#dlicom-creators</strong> में सक्रिय।',
    hrole4_tag: '🔹 जूनियर हंटर',
    hrole4_desc: 'फॉर्म भरें और यह विशेष रोल पाएँ — <strong>#nominations</strong> और अन्य प्राइवेट चैनलों तक पहुँच मिलती है।',
    hrole4_link: 'फॉर्म भरें →',
    sec_phases: 'हंट के <span class="acc">चरण</span>',
    phase1_label: 'चरण 1',
    phase1_title: 'अपनी पहचान बनाएँ',
    phase1_dates: '27 फ़र — 11 मार',
    phase1_desc: 'प्रारंभिक चयन। नॉमिनेशन चैनल खुलता है। टीम देखती है, मदद करती है और सभी को सही दिशा में गाइड करती है।',
    phase1_li1: 'प्रति क्षेत्र 10 Dliever रोल',
    phase1_li2: 'फॉर्म भरने वालों के लिए नॉमिनेशन खुले',
    phase1_li3: 'जूनियर हंटर रोल उपलब्ध',
    phase2_label: 'चरण 2',
    phase2_title: 'ट्रायल पीरियड',
    phase2_dates: '12 मार — 19 मार',
    phase2_desc: 'प्रति क्षेत्र टॉप 5 उम्मीदवार कम्युनिटी टीम के साथ काम शुरू करते हैं। चयनित उम्मीदवार Dliever और Dcoded के लिए लोगों को नॉमिनेट कर सकते हैं।',
    phase2_li1: 'प्रति क्षेत्र 5 Dcoded रोल',
    phase2_li2: 'केवल Dliever को Dcoded मिल सकता है',
    phase2_li3: 'टीम के साथ सीधा सहयोग',
    phase3_label: 'चरण 3',
    phase3_title: 'फाइनल',
    phase3_dates: '20 मार — 27 मार',
    phase3_desc: 'लीड और मॉड नियुक्त, रोल और अनुमतियाँ सौंपी गईं। सबसे कठिन रोल — Dlicom Contribution Officer — उपलब्ध होता है।',
    phase3_li1: 'प्रति क्षेत्र 1 DCO रोल',
    phase3_li2: 'Dcoded + Dlicom सर्वर टैग होना चाहिए',
    phase3_li3: 'Regional Lead और Helper नियुक्त',
    results_title: 'प्रति क्षेत्र परिणाम',
    res_p1: '(चरण 1)',
    res_p2: '(चरण 2)',
    res_p3: '(चरण 3)',
    sec_roles: 'कम्युनिटी <span class="acc">रोल</span>',
    role1_desc: 'ऐसे अग्रदूत जिन्होंने अपनी विश्वसनीयता और Dlicom का ज्ञान साबित किया। सबसे ज़्यादा मांग वाला बेस रोल — सब कुछ की शुरुआत।',
    role2_desc: 'सक्रिय और समर्पित सदस्य — नए लोगों के लिए उदाहरण। Dliever रोल आवश्यक।',
    role3_desc: 'Dlicom Contribution Officer। सबसे दुर्लभ रोल। Dcoded + सर्वर टैग आवश्यक।',
    role4_desc: 'पहले 1000 पौराणिक यूज़र। एयरड्रॉप बूस्ट, बोनस XP। अब नहीं दिया जाता।',
    sec_rules: 'कम्युनिटी <span class="acc">नियम</span>',
    rule1_title: 'प्रतिबंधित',
    rule1_desc: 'राजनीति, नस्लवाद, भेदभाव। अश्लील सामग्री। स्पैम और सेल्फ-प्रमोशन। थीम्ड चैनलों में ऑफ-टॉपिक।',
    rule2_title: 'स्वागत है',
    rule2_desc: 'नए लोगों की मदद करें, खुद बढ़ें, संपर्क बनाएँ। विचारों को कार्रवाई में बदलें। अपना आप बनें।',
    rule3_title: 'स्कैम से सावधान रहें',
    rule3_desc: 'Dlicom टीम <strong>DM में पहले कभी मैसेज नहीं करेगी</strong>। हमेशा सत्यापित करें।',
    rule4_title: 'कम्युनिटी सिद्धांत',
    rule4_desc: 'मूल्य ही सब कुछ है। <strong>#creators</strong> चैनल रोल पाने का सबसे भरोसेमंद तरीका है।',
    sec_token: 'टोकेनो<span class="acc">मिक्स</span>',
    leg1: 'नेटवर्क सेल',
    leg2: 'पब्लिक प्री सेल',
    leg3: 'लिक्विडिटी',
    leg4: 'पब्लिक सेल',
    leg5: 'ट्रेजरी और रिज़र्व',
    leg6: 'इकोसिस्टम / खर्च',
    leg7: 'फाउंडर्स और टीम',
    leg8: 'कम्युनिटी / यूज़र इंसेंटिव',
    leg9: 'एडवाइज़री',
    sec_tokdet: 'टोकन विवरण <span class="acc">$DLI</span>',
    tok_standard: 'मानक',
    tok_supply: 'कुल आपूर्ति',
    tok_price: 'प्रारंभिक मूल्य',
    tok_circ: 'प्रारंभिक सर्कुलेशन',
    tok_cap: 'प्रारंभिक मार्केट कैप',
    tok_lp: 'लिक्विडिटी पूल',
    tok_vest: 'वेस्टिंग',
    tok_vest_val: '0–60 महीने',
    tok_dec: 'दशमलव',
    sec_team: 'Dlicom <span class="acc">टीम</span>',
    team1_role: 'चेयरमैन और सह-संस्थापक',
    team2_role: 'टोकेनोमिक्स प्रमुख',
    team3_role: 'कम्युनिटी मैनेजर',
    team4_role: 'प्रोडक्ट मैनेजर',
    sec_faq: 'अक्सर पूछे जाने वाले <span class="acc">प्रश्न</span>',
    faq0_q: 'जूनियर हंटर रोल क्या है?',
    faq0_a: '<a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">आवेदन फॉर्म</a> भरें और जूनियर हंटर रोल पाएँ — यह हंट के दौरान <strong>#nominations</strong> और अन्य प्राइवेट चैनलों तक पहुँच देता है।',
    faqA_q: 'Regional Lead और Regional Helper में क्या फर्क है?',
    faqA_a: '<strong>Regional Lead</strong> क्षेत्र का कम्युनिटी मैनेजर है: विकास, रिटेंशन, कैंपेन, एनालिटिक्स। <strong>Regional Helper</strong> लीडर का सहायक है: सवालों के जवाब, सदस्यों की गाइडेंस, इवेंट, चैट एक्टिविटी।',
    faq1_q: 'Regional Lead कैसे बनें?',
    faq1_a: '1. <a href="https://forms.gle/LT9mZUa1KyUmxrZ1A" target="_blank">आवेदन फॉर्म</a> भरें। 2. Discord में अपना क्षेत्र चुनें। 3. तीनों चरणों में सक्रिय भाग लें (27 Feb — 27 Mar)।',
    faq2_q: 'क्या Regional Hunt में शामिल होने के लिए Dliever ज़रूरी है?',
    faq2_a: 'नहीं। आवेदन के लिए Dliever ज़रूरी नहीं। लेकिन सक्रिय प्रतिभागी इसे अपने आप पाते हैं और चयन में प्राथमिकता मिलती है।',
    faq3_q: 'DLI टोकन क्या है?',
    faq3_a: 'DLI Ethereum पर Dlicom का नेटिव टोकन है। इसका उपयोग: चैट में क्रिप्टो भेजने, टिप्स, गैस पेमेंट, USDT रिवार्ड के साथ स्टेकिंग और वोटिंग के लिए होता है।',
    faq4_q: 'क्या KYC ज़रूरी है?',
    faq4_a: 'नहीं। Dlicom DEX के रूप में काम करने वाला पूरी तरह विकेंद्रीकृत प्रोजेक्ट है। KYC ज़रूरी नहीं। प्रोफाइल Ethereum पते पर आधारित हैं।',
    faq5_q: 'Dili मस्कट कॉन्टेस्ट क्या है?',
    faq5_a: 'Dili के बारे में कहानी, लोर या कॉन्सेप्ट बनाएँ (टेक्स्ट, वीडियो, आर्ट)। टॉप 10 आइडिया Dliever रोल पाते हैं। <code>#creators</code> में <a href="https://x.com/DlicomApp/status/2023744462434783676" target="_blank">X पोस्ट</a> कोट करके पोस्ट करें।',
    faq6_q: 'प्लेटफ़ॉर्म पर कैसे कमाएँ?',
    faq6_a: '<code>स्टेकिंग</code> — USDT रिवार्ड के लिए DLI। <code>कंटेंट</code> — फॉलोअर से टिप्स। <code>रेफरल</code> — अपने कोड से इनवाइट करें।',
    faq7_q: 'क्या मैं Helper को छोड़कर सीधे Regional Lead के लिए आवेदन कर सकता हूँ?',
    faq7_a: 'हाँ। Regional Lead के लिए आवेदन करके आप स्वतः Regional Helper के उम्मीदवार भी बन जाते हैं।',
    faq8_q: 'अभी क्यों जुड़ने का सबसे अच्छा समय है?',
    faq8_a: 'यह सबसे प्रारंभिक चरण है — क्षेत्रों में अभी कोई मॉडरेटर या लीड नहीं है। अभी शून्य से शुरू करना Regional Lead या Helper बनने का सबसे अच्छा अवसर है।',
    sec_links: 'आधिकारिक <span class="acc">लिंक</span>',
    link_wp: 'श्वेतपत्र',
    link_tgoff: 'Telegram आधिकारिक',
    link_tgcis: 'Telegram CIS',
    link_yt: 'YouTube',
    link_med: 'Medium ब्लॉग',
    sec_news: 'Discord <span class="acc">अपडेट</span>',
    news1_date: '2 मार 2025',
    news_badge_new: 'नया',
    news1_title: '📌 #content-spotlight — रेड सेलेक्शन',
    news1_body: 'Discord में नया चैनल <strong>#content-spotlight</strong> आया है — बेस्ट कम्युनिटी कंटेंट का शोकेस। मॉडरेटर क्रिएटर्स के पोस्ट चुनकर वहाँ फीचर करेंगे, फिर टॉप वर्क पर पूरी रेड ऑर्गेनाइज़ करेंगे। अगर आपका पोस्ट <strong>#content-spotlight</strong> में पहुँचा, तो टीम इसे अधिकतम पहुँच का पात्र मानती है। यह हंट के सैकड़ों प्रतिभागियों में अलग दिखने का मौका है।',
    news_tag_announce: '📣 घोषणा',
    news2_date: '27 फ़र 2025',
    news_badge_phase1: 'चरण 1',
    news2_title: '🚀 Regional Hunt लॉन्च',
    news2_body: 'Regional Lead और Regional Helper के लिए आवेदन आधिकारिक रूप से खुल गए हैं। <strong>#nominations</strong> चैनल जूनियर हंटर रोल धारकों के लिए अनलॉक है। अभी आवेदन करें और पहलों में शामिल हों।',
    news_tag_hunt: '🏹 हंट',
    news3_date: 'फ़र 2025',
    news_badge_info: 'जानकारी',
    news3_title: '🎭 Dili लोर कॉन्टेस्ट',
    news3_body: 'Dili मस्कट के बारे में कहानी, आर्ट या कॉन्सेप्ट बनाएँ। टॉप 10 एंट्री को अपने आप <strong>Dliever</strong> रोल मिलता है। आधिकारिक X पोस्ट कोट करते हुए <code>#creators</code> में पोस्ट करें।',
    news_tag_creators: '🎨 क्रिएटर्स',
    news4_date: '5 मार 2025',
    news4_title: '🛡️ टेस्ट मॉडरेटर नियुक्त',
    news4_body: 'Discord सर्वर में 6 टेस्ट मॉडरेटर नियुक्त किए गए हैं। 2 सप्ताह के ट्रायल पीरियड के बाद उनमें से 2 स्थायी मॉडरेटर बनेंगे। चयन प्रक्रिया जारी है — सर्वश्रेष्ठ बने रहेंगे।',
    news_tag_mod: '🛡️ मॉडरेशन',
    cta_title: 'कम्युनिटी हब से जुड़ने के लिए तैयार हैं?',
    cta_desc: 'Discord से जुड़ें, अपना क्षेत्र चुनें और Regional Hunt में भाग लें',
    cta_btn1: '↗ Discord खोलें',
    cta_btn2: 'अभी आवेदन करें',
    footer_brand: 'कम्युनिटी हब · अनौपचारिक संसाधन',
    footer_apply: 'आवेदन फॉर्म',
    footer_discord: '',
    footer_discord_txt: 'सर्वर से जुड़ें',
    nav_tg_news: 'TG समाचार',
    tg_post_title: '<strong>Regional Hunt: अगला चरण 11 मार्च को होगा! 🗺️</strong>',
    tg_post_body: 'सीजन 1 आज 00:00 UTC पर रूस, यूक्रेन, नाइजीरिया, वियतनाम, अरबी क्षेत्र और भारत के लिए समाप्त होता है। यदि आप एक निर्माता, योगदानकर्ता या सामुदायिक निर्माता हैं — अब आपका समय है!',
    tg_news_open: 'Discord खोलें',
    tg_post_form: '👉 Dlicom Discord',
    news10_date: '10 मार 2025',
    news10_title: '🗺️ Regional Hunt: अगला चरण 11 मार्च को होगा!',
    news10_body: 'सीजन 1 आज 00:00 UTC पर रूस, यूक्रेन, नाइजीरिया, वियतनाम, अरबी क्षेत्र और भारत के लिए समाप्त होता है। यदि आप एक निर्माता, योगदानकर्ता या सामुदायिक निर्माता हैं — अब आपका समय है!',
    news10_btn: 'Dlicom Discord →',
    news7_date: '8 मार 2025',
    news7_title: '🎯 फेज़ 1 समाप्त हो रहा — रोल कैसे काम करते हैं',
    news7_body: '11 मार्च को फेज़ 1 समाप्त होगा। ~60 <strong>Dliever</strong> और ~30 ट्रायल स्पॉट चुने जाएंगे। <strong>Regional Lead</strong> — क्षेत्र का चेहरा, ग्रोथ और कम्युनिटी मैनेजमेंट। <strong>Regional Helper (Mod)</strong> — अनुवाद, इवेंट, मॉडरेशन। <strong>Dliever और अन्य रोल</strong> — <code>#creators</code> में कंटेंट क्रिएशन।',
    news7_btn: 'फॉर्म भरें →',
    news8_date: '8 मार 2025',
    news8_title: '📺 साप्ताहिक Community Spotlight — लाइव रिव्यू',
    news8_body: '8 मार्च 19:00 बजे — टीम लाइव आकर बेहतरीन कम्युनिटी कार्यों की समीक्षा करेगी और वास्तविक फीडबैक देगी। <a href="https://docs.google.com/forms/d/e/1FAlpQLSc1cJCwTX-bJc1R41CMucUuTGMrYdlqjQXq03aoArXEz3cyyg/viewform" target="_blank">अपना काम भेजें</a>।',
    news9_date: '7 मार 2025',
    news9_title: '💼 भर्ती: पार्ट-टाइम SMM टीममेट',
    news9_body: 'Dlicom पार्ट-टाइम SMM टीम मेंबर की तलाश में है। Web3 में सहज होना चाहिए, ट्रेंड फॉलो करें और X व Telegram के लिए नेटिव कंटेंट बनाएं। डेडलाइन: 20 मार्च। <a href="https://forms.gle/qvBF4vKm8ynGPD618" target="_blank">अभी आवेदन करें</a>।',
    news_tag_team: '💼 टीम',
  }
};


// ── Apply Language ─────────────────────────────────────────────
function applyLang(lang) {
  const t = T[lang] || T.en;
  document.documentElement.lang = lang;
  // RTL support for Arabic
  if (lang === 'ar') {
    document.documentElement.dir = 'rtl';
    document.documentElement.setAttribute('dir', 'rtl');
  } else {
    document.documentElement.dir = 'ltr';
    document.documentElement.setAttribute('dir', 'ltr');
  }
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  // Show tournament card only for RU and UK
  const news5 = document.getElementById('news5');
  if (news5) news5.style.display = (lang === 'ru' || lang === 'uk') ? '' : 'none';
}

// ── Nav scroll effect ──────────────────────────────────────────
window.addEventListener('scroll', () => {
  const nav = document.querySelector('nav');
  if (nav) nav.classList.toggle('scrolled', window.scrollY > 40);
});

// ── TG News Popup ─────────────────────────────────────────────
(function initTgPopup() {
  const trigger = document.getElementById('tgNewsTrigger');
  const popup = document.getElementById('tgNewsPopup');
  const closeBtn = document.getElementById('tgNewsClose');
  if (!trigger || !popup) return;

  trigger.addEventListener('click', e => {
    e.preventDefault();
    e.stopPropagation();
    popup.classList.toggle('open');
  });
  if (closeBtn) closeBtn.addEventListener('click', e => {
    e.stopPropagation();
    popup.classList.remove('open');
  });
  document.addEventListener('click', e => {
    if (!popup.contains(e.target) && !trigger.contains(e.target)) {
      popup.classList.remove('open');
    }
  });
})();
